var h,s={};window.Vadstena=s;window.ga=null!=window.ga?window.ga:{};window.VadstenaMap_=null!=window.VadstenaMap_?window.VadstenaMap_:null;s.ua=Array;s.Bd={};s.Bd.create=function(a){var b=new s.ua(2);a&&(b[0]=a[0],b[1]=a[1]);return b};s.Sb={};s.Sb.create=function(a){var b=new s.ua(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b};s.Sb.Xb=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]};s.I={};s.I.create=function(a){var b=new s.ua(3);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2]);return b};s.I.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b};
s.I.add=function(a,b,c){if(!c||a==c)return a[0]+=b[0],a[1]+=b[1],a[2]+=b[2],a;c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c};s.I.Td=function(a,b,c){if(!c||a==c)return a[0]-=b[0],a[1]-=b[1],a[2]-=b[2],a;c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c};s.I.Md=function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b};s.I.scale=function(a,b,c){if(!c||a==c)return a[0]*=b,a[1]*=b,a[2]*=b,a;c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c};
s.I.normalize=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=Math.sqrt(c*c+d*d+e*e);if(f){if(1==f)return b[0]=c,b[1]=d,b[2]=e,b}else return b[0]=0,b[1]=0,b[2]=0,b;f=1/f;b[0]=c*f;b[1]=d*f;b[2]=e*f;return b};s.I.Fd=function(a,b,c){c||(c=a);var d=a[0],e=a[1];a=a[2];var f=b[0],g=b[1];b=b[2];c[0]=e*b-a*g;c[1]=a*f-d*b;c[2]=d*g-e*f;return c};s.I.length=function(a){var b=a[0],c=a[1];a=a[2];return Math.sqrt(b*b+c*c+a*a)};s.I.Xb=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]};
s.I.direction=function(a,b,c){c||(c=a);var d=a[0]-b[0],e=a[1]-b[1];a=a[2]-b[2];b=Math.sqrt(d*d+e*e+a*a);if(!b)return c[0]=0,c[1]=0,c[2]=0,c;b=1/b;c[0]=d*b;c[1]=e*b;c[2]=a*b;return c};s.I.Id=function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);return d};s.I.Ob=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+"]"};s.Z={};
s.Z.create=function(a){var b=new s.ua(9);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9]);return b};s.Z.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b};s.Z.hc=function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a};
s.Z.xa=function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[5];a[1]=a[3];a[2]=a[6];a[3]=c;a[5]=a[7];a[6]=d;a[7]=e;return a}b[0]=a[0];b[1]=a[3];b[2]=a[6];b[3]=a[1];b[4]=a[4];b[5]=a[7];b[6]=a[2];b[7]=a[5];b[8]=a[8];return b};s.Z.Ad=function(a,b){b||(b=s.b.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=0;b[4]=a[3];b[5]=a[4];b[6]=a[5];b[7]=0;b[8]=a[6];b[9]=a[7];b[10]=a[8];b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};
s.Z.Ob=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+"]"};s.b={};s.b.create=function(a){var b=new s.ua(16);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9],b[10]=a[10],b[11]=a[11],b[12]=a[12],b[13]=a[13],b[14]=a[14],b[15]=a[15]);return b};
s.b.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b};s.b.hc=function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};
s.b.xa=function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[3],f=a[6],g=a[7],k=a[11];a[1]=a[4];a[2]=a[8];a[3]=a[12];a[4]=c;a[6]=a[9];a[7]=a[13];a[8]=d;a[9]=f;a[11]=a[14];a[12]=e;a[13]=g;a[14]=k;return a}b[0]=a[0];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=a[1];b[5]=a[5];b[6]=a[9];b[7]=a[13];b[8]=a[2];b[9]=a[6];b[10]=a[10];b[11]=a[14];b[12]=a[3];b[13]=a[7];b[14]=a[11];b[15]=a[15];return b};
s.b.Gd=function(a){var b=a[0],c=a[1],d=a[2],e=a[3],f=a[4],g=a[5],k=a[6],l=a[7],m=a[8],n=a[9],p=a[10],q=a[11],r=a[12],t=a[13],v=a[14];a=a[15];return r*n*k*e-m*t*k*e-r*g*p*e+f*t*p*e+m*g*v*e-f*n*v*e-r*n*d*l+m*t*d*l+r*c*p*l-b*t*p*l-m*c*v*l+b*n*v*l+r*g*d*q-f*t*d*q-r*c*k*q+b*t*k*q+f*c*v*q-b*g*v*q-m*g*d*a+f*n*d*a+m*c*k*a-b*n*k*a-f*c*p*a+b*g*p*a};
s.b.inverse=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],k=a[5],l=a[6],m=a[7],n=a[8],p=a[9],q=a[10],r=a[11],t=a[12],v=a[13],y=a[14],z=a[15],H=c*k-d*g,I=c*l-e*g,A=c*m-f*g,B=d*l-e*k,C=d*m-f*k,D=e*m-f*l,E=n*v-p*t,F=n*y-q*t,G=n*z-r*t,J=p*y-q*v,K=p*z-r*v,L=q*z-r*y,w=1/(H*L-I*K+A*J+B*G-C*F+D*E);b[0]=(k*L-l*K+m*J)*w;b[1]=(-d*L+e*K-f*J)*w;b[2]=(v*D-y*C+z*B)*w;b[3]=(-p*D+q*C-r*B)*w;b[4]=(-g*L+l*G-m*F)*w;b[5]=(c*L-e*G+f*F)*w;b[6]=(-t*D+y*A-z*I)*w;b[7]=(n*D-q*A+r*I)*w;b[8]=(g*K-k*G+m*E)*w;b[9]=
(-c*K+d*G-f*E)*w;b[10]=(t*C-v*A+z*H)*w;b[11]=(-n*C+p*A-r*H)*w;b[12]=(-g*J+k*F-l*E)*w;b[13]=(c*J-d*F+e*E)*w;b[14]=(-t*B+v*I-y*H)*w;b[15]=(n*B-p*I+q*H)*w;return b};s.b.Vd=function(a,b){b||(b=s.b.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};
s.b.zd=function(a,b){b||(b=s.Z.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b};s.b.Ud=function(a,b){var c=a[0],d=a[1],e=a[2],f=a[4],g=a[5],k=a[6],l=a[8],m=a[9],n=a[10],p=n*g-k*m,q=-n*f+k*l,r=m*f-g*l,t=c*p+d*q+e*r;if(!t)return null;t=1/t;b||(b=s.Z.create());b[0]=p*t;b[1]=(-n*d+e*m)*t;b[2]=(k*d-e*g)*t;b[3]=q*t;b[4]=(n*c-e*l)*t;b[5]=(-k*c+e*f)*t;b[6]=r*t;b[7]=(-m*c+d*l)*t;b[8]=(g*c-d*f)*t;return b};
s.b.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],f=a[2],g=a[3],k=a[4],l=a[5],m=a[6],n=a[7],p=a[8],q=a[9],r=a[10],t=a[11],v=a[12],y=a[13],z=a[14];a=a[15];var H=b[0],I=b[1],A=b[2],B=b[3],C=b[4],D=b[5],E=b[6],F=b[7],G=b[8],J=b[9],K=b[10],L=b[11],w=b[12],X=b[13],Y=b[14];b=b[15];c[0]=H*d+I*k+A*p+B*v;c[1]=H*e+I*l+A*q+B*y;c[2]=H*f+I*m+A*r+B*z;c[3]=H*g+I*n+A*t+B*a;c[4]=C*d+D*k+E*p+F*v;c[5]=C*e+D*l+E*q+F*y;c[6]=C*f+D*m+E*r+F*z;c[7]=C*g+D*n+E*t+F*a;c[8]=G*d+J*k+K*p+L*v;c[9]=G*e+J*l+K*q+L*y;c[10]=G*f+
J*m+K*r+L*z;c[11]=G*g+J*n+K*t+L*a;c[12]=w*d+X*k+Y*p+b*v;c[13]=w*e+X*l+Y*q+b*y;c[14]=w*f+X*m+Y*r+b*z;c[15]=w*g+X*n+Y*t+b*a;return c};s.b.bb=function(a,b,c){c||(c=b);var d=b[0],e=b[1];b=b[2];c[0]=a[0]*d+a[4]*e+a[8]*b+a[12];c[1]=a[1]*d+a[5]*e+a[9]*b+a[13];c[2]=a[2]*d+a[6]*e+a[10]*b+a[14];return c};s.b.cb=function(a,b,c){c||(c=b);var d=b[0],e=b[1],f=b[2];b=b[3];c[0]=a[0]*d+a[4]*e+a[8]*f+a[12]*b;c[1]=a[1]*d+a[5]*e+a[9]*f+a[13]*b;c[2]=a[2]*d+a[6]*e+a[10]*f+a[14]*b;c[3]=a[3]*d+a[7]*e+a[11]*f+a[15]*b;return c};
s.b.translate=function(a,b,c){var d=b[0],e=b[1];b=b[2];if(!c||a==c)return a[12]=a[0]*d+a[4]*e+a[8]*b+a[12],a[13]=a[1]*d+a[5]*e+a[9]*b+a[13],a[14]=a[2]*d+a[6]*e+a[10]*b+a[14],a[15]=a[3]*d+a[7]*e+a[11]*b+a[15],a;var f=a[0],g=a[1],k=a[2],l=a[3],m=a[4],n=a[5],p=a[6],q=a[7],r=a[8],t=a[9],v=a[10],y=a[11];c[0]=f;c[1]=g;c[2]=k;c[3]=l;c[4]=m;c[5]=n;c[6]=p;c[7]=q;c[8]=r;c[9]=t;c[10]=v;c[11]=y;c[12]=f*d+m*e+r*b+a[12];c[13]=g*d+n*e+t*b+a[13];c[14]=k*d+p*e+v*b+a[14];c[15]=l*d+q*e+y*b+a[15];return c};
s.b.scale=function(a,b,c){var d=b[0],e=b[1];b=b[2];if(!c||a==c)return a[0]*=d,a[1]*=d,a[2]*=d,a[3]*=d,a[4]*=e,a[5]*=e,a[6]*=e,a[7]*=e,a[8]*=b,a[9]*=b,a[10]*=b,a[11]*=b,a;c[0]=a[0]*d;c[1]=a[1]*d;c[2]=a[2]*d;c[3]=a[3]*d;c[4]=a[4]*e;c[5]=a[5]*e;c[6]=a[6]*e;c[7]=a[7]*e;c[8]=a[8]*b;c[9]=a[9]*b;c[10]=a[10]*b;c[11]=a[11]*b;c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15];return c};
s.b.rotate=function(a,b,c,d){var e=c[0],f=c[1];c=c[2];var g=Math.sqrt(e*e+f*f+c*c);if(!g)return null;1!=g&&(g=1/g,e*=g,f*=g,c*=g);var k=Math.sin(b),l=Math.cos(b),m=1-l;b=a[0];var g=a[1],n=a[2],p=a[3],q=a[4],r=a[5],t=a[6],v=a[7],y=a[8],z=a[9],H=a[10],I=a[11],A=e*e*m+l,B=f*e*m+c*k,C=c*e*m-f*k,D=e*f*m-c*k,E=f*f*m+l,F=c*f*m+e*k,G=e*c*m+f*k,e=f*c*m-e*k,f=c*c*m+l;d?a!=d&&(d[12]=a[12],d[13]=a[13],d[14]=a[14],d[15]=a[15]):d=a;d[0]=b*A+q*B+y*C;d[1]=g*A+r*B+z*C;d[2]=n*A+t*B+H*C;d[3]=p*A+v*B+I*C;d[4]=b*D+q*
E+y*F;d[5]=g*D+r*E+z*F;d[6]=n*D+t*E+H*F;d[7]=p*D+v*E+I*F;d[8]=b*G+q*e+y*f;d[9]=g*G+r*e+z*f;d[10]=n*G+t*e+H*f;d[11]=p*G+v*e+I*f;return d};s.b.Pd=function(a,b,c){var d=Math.sin(b);b=Math.cos(b);var e=a[4],f=a[5],g=a[6],k=a[7],l=a[8],m=a[9],n=a[10],p=a[11];c?a!=c&&(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[4]=e*b+l*d;c[5]=f*b+m*d;c[6]=g*b+n*d;c[7]=k*b+p*d;c[8]=e*-d+l*b;c[9]=f*-d+m*b;c[10]=g*-d+n*b;c[11]=k*-d+p*b;return c};
s.b.Qd=function(a,b,c){var d=Math.sin(b);b=Math.cos(b);var e=a[0],f=a[1],g=a[2],k=a[3],l=a[8],m=a[9],n=a[10],p=a[11];c?a!=c&&(c[4]=a[4],c[5]=a[5],c[6]=a[6],c[7]=a[7],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+l*-d;c[1]=f*b+m*-d;c[2]=g*b+n*-d;c[3]=k*b+p*-d;c[8]=e*d+l*b;c[9]=f*d+m*b;c[10]=g*d+n*b;c[11]=k*d+p*b;return c};
s.b.Rd=function(a,b,c){var d=Math.sin(b);b=Math.cos(b);var e=a[0],f=a[1],g=a[2],k=a[3],l=a[4],m=a[5],n=a[6],p=a[7];c?a!=c&&(c[8]=a[8],c[9]=a[9],c[10]=a[10],c[11]=a[11],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+l*d;c[1]=f*b+m*d;c[2]=g*b+n*d;c[3]=k*b+p*d;c[4]=e*-d+l*b;c[5]=f*-d+m*b;c[6]=g*-d+n*b;c[7]=k*-d+p*b;return c};
s.b.Oc=function(a,b,c,d,e,f,g){g||(g=s.b.create());var k=b-a,l=d-c,m=f-e;g[0]=2*e/k;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=2*e/l;g[6]=0;g[7]=0;g[8]=(b+a)/k;g[9]=(d+c)/l;g[10]=-(f+e)/m;g[11]=-1;g[12]=0;g[13]=0;g[14]=-(f*e*2)/m;g[15]=0;return g};s.b.perspective=function(a,b,c,d,e){a=c*Math.tan(a*Math.PI/360);b*=a;return s.b.Oc(-b,b,-a,a,c,d,e)};
s.b.Od=function(a,b,c,d,e,f,g){g||(g=s.b.create());var k=b-a,l=d-c,m=f-e;g[0]=2/k;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=2/l;g[6]=0;g[7]=0;g[8]=0;g[9]=0;g[10]=-2/m;g[11]=0;g[12]=-(a+b)/k;g[13]=-(d+c)/l;g[14]=-(f+e)/m;g[15]=1;return g};
s.b.Jd=function(a,b,c,d){d||(d=s.b.create());var e=a[0],f=a[1];a=a[2];var g=c[0],k=c[1],l=c[2];c=b[1];var m=b[2];if(e==b[0]&&f==c&&a==m)return s.b.hc(d);var n,p,q,r;c=e-b[0];m=f-b[1];b=a-b[2];r=1/Math.sqrt(c*c+m*m+b*b);c*=r;m*=r;b*=r;n=k*b-l*m;l=l*c-g*b;g=g*m-k*c;(r=Math.sqrt(n*n+l*l+g*g))?(r=1/r,n*=r,l*=r,g*=r):g=l=n=0;k=m*g-b*l;p=b*n-c*g;q=c*l-m*n;(r=Math.sqrt(k*k+p*p+q*q))?(r=1/r,k*=r,p*=r,q*=r):q=p=k=0;d[0]=n;d[1]=k;d[2]=c;d[3]=0;d[4]=l;d[5]=p;d[6]=m;d[7]=0;d[8]=g;d[9]=q;d[10]=b;d[11]=0;d[12]=
-(n*e+l*f+g*a);d[13]=-(k*e+p*f+q*a);d[14]=-(c*e+m*f+b*a);d[15]=1;return d};s.b.Ob=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+"]"};s.P={};s.P.create=function(a){var b=new s.ua(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b};s.P.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b};
s.P.Ed=function(a,b){var c=a[0],d=a[1],e=a[2];if(!b||a==b)return a[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e)),a;b[0]=c;b[1]=d;b[2]=e;b[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e));return b};s.P.inverse=function(a,b){if(!b||a==b)return a[0]*=1,a[1]*=1,a[2]*=1,a;b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b};s.P.length=function(a){var b=a[0],c=a[1],d=a[2];a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)};
s.P.normalize=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],f=a[3],g=Math.sqrt(c*c+d*d+e*e+f*f);if(0==g)return b[0]=0,b[1]=0,b[2]=0,b[3]=0,b;g=1/g;b[0]=c*g;b[1]=d*g;b[2]=e*g;b[3]=f*g;return b};s.P.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],f=a[2];a=a[3];var g=b[0],k=b[1],l=b[2];b=b[3];c[0]=d*b+a*g+e*l-f*k;c[1]=e*b+a*k+f*g-d*l;c[2]=f*b+a*l+d*k-e*g;c[3]=a*b-d*g-e*k-f*l;return c};
s.P.bb=function(a,b,c){c||(c=b);var d=b[0],e=b[1],f=b[2];b=a[0];var g=a[1],k=a[2];a=a[3];var l=a*d+g*f-k*e,m=a*e+k*d-b*f,n=a*f+b*e-g*d,d=-b*d-g*e-k*f;c[0]=l*a+d*-b+m*-k-n*-g;c[1]=m*a+d*-g+n*-b-l*-k;c[2]=n*a+d*-k+l*-g-m*-b;return c};s.P.zd=function(a,b){b||(b=s.Z.create());var c=a[0],d=a[1],e=a[2],f=a[3],g=c+c,k=d+d,l=e+e,m=c*g,n=c*k,c=c*l,p=d*k,d=d*l,e=e*l,g=f*g,k=f*k,f=f*l;b[0]=1-(p+e);b[1]=n-f;b[2]=c+k;b[3]=n+f;b[4]=1-(m+e);b[5]=d-g;b[6]=c-k;b[7]=d+g;b[8]=1-(m+p);return b};
s.P.Ad=function(a,b){b||(b=s.b.create());var c=a[0],d=a[1],e=a[2],f=a[3],g=c+c,k=d+d,l=e+e,m=c*g,n=c*k,c=c*l,p=d*k,d=d*l,e=e*l,g=f*g,k=f*k,f=f*l;b[0]=1-(p+e);b[1]=n-f;b[2]=c+k;b[3]=0;b[4]=n+f;b[5]=1-(m+e);b[6]=d-g;b[7]=0;b[8]=c-k;b[9]=d+g;b[10]=1-(m+p);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};s.P.Sd=function(a,b,c,d){d||(d=a);var e=c;0>a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]&&(e=-1*c);d[0]=1-c*a[0]+e*b[0];d[1]=1-c*a[1]+e*b[1];d[2]=1-c*a[2]+e*b[2];d[3]=1-c*a[3]+e*b[3];return d};
s.P.Ob=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"};s.Pc=function(a,b,c,d,e,f){var g=b-a,k=d-c,l=f-e;a=s.b.create([2*e/g,0,(b+a)/g,0,0,2*e/k,(d+c)/k,0,0,0,-(f+e)/l,-2*f*e/l,0,0,-1,0]);s.b.xa(a);return a};s.hd=function(a,b,c,d){a=c*Math.tan(a*Math.PI/360);b*=a;return s.Pc(-b,b,-a,a,c,d)};s.La=function(a,b){var c=Math.cos(b),d=Math.sin(b);switch(a){case 0:c=s.b.create([1,0,0,0,0,c,-d,0,0,d,c,0,0,0,0,1]);break;case 1:c=s.b.create([c,0,-d,0,0,1,0,0,d,0,c,0,0,0,0,1]);break;default:c=s.b.create([c,-d,0,0,d,c,0,0,0,0,1,0,0,0,0,1])}s.b.xa(c);return c};
s.mb=function(a,b,c){a=s.b.create([a,0,0,0,0,b,0,0,0,0,c,0,0,0,0,1]);s.b.xa(a);return a};s.od=function(a){return s.mb(a,a,a)};s.sa=function(a,b,c){a=s.b.create([1,0,0,a,0,1,0,b,0,0,1,c,0,0,0,1]);s.b.xa(a);return a};s.Wd=function(a){return s.sa(a[0],a[1],0)};s.Xd=function(a){return s.sa(a[0],a[1],a[2])};s.ja=function(a,b,c){a<b?a=b:a>c&&(a=c);return a};s.X=function(a){return a*Math.PI/180};s.tc=function(a){var b=7;if(0>a)return a=-a+"",b--,a.length>=b?"-"+a:"-"+(Array(b-a.length+1).join("0")+a);a+="";return a.length>=b?a:Array(b-a.length+1).join("0")+a};s.sd=function(a,b){return a.replace(/\{([_$a-zA-Z0-9][_$a-zA-Z0-9]*)\}/g,function(a,d){return d in b?b[d]:a})};
s.kc=function(a,b,c){var d=new XMLHttpRequest;d.onload=function(){var a=d.response;try{var f=eval("("+a+")")}catch(g){null!=c&&c();return}null!=b&&b(f)}.bind(this);d.onerror=function(){null!=c&&c()}.bind(this);d.open("GET",a,!0);d.send("")};
s.jc=function(a,b,c){var d=new XMLHttpRequest;d.onreadystatechange=function(){switch(d.readyState){case 0:case 1:case 2:case 3:break;case 4:if(404==d.status){null!=c&&c();break}var a=new DataView(d.response);null!=b&&b(a);break;default:null!=c&&c()}}.bind(this);d.onerror=function(){null!=c&&c()}.bind(this);d.open("GET",a,!0);d.responseType="arraybuffer";d.send("")};window.performance=window.performance||{};
performance.now=performance.now||performance.Kd||performance.Ld||performance.Nd||performance.webkitNow||function(){return(new Date).getTime()};window.yc=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};function aa(a,b,c){this.A=new u(a);this.nc=this.oc=this.yb=0;this.Wa=[];this.Va=[0,0,0];this.Jc=c;this.Cc=this.mc=this.pc="";null!=b.foat&&(this.A.l=b.foat[0],this.A.r=b.foat[1],this.A.s=b.foat[2],this.yb=b.foat[3]);null!=b.meta&&(this.oc=b.meta[0],this.nc=b.meta[1]);this.pc=b.metaTemplate;this.mc=b.meshTemplate;this.Cc=b.textureTemplate;if(null!=b.defaultPosition&&null!=b.defaultOrientation)for(a=0;3>a;a++)this.Wa[a]=b.defaultPosition[a],this.Va[a]=b.defaultOrientation[a]}
function x(a,b){return b>a.A.l?a.yb>>b-a.A.l:a.yb<<a.A.l-b}function ba(a,b){return ca(a,a.pc,b)}function da(a,b){return ca(a,a.mc,b)}function ea(a,b){return ca(a,a.Cc,b)}function ca(a,b,c){b=s.sd(b,{lod:c.l,easting:s.tc(c.r),northing:s.tc(c.s)});return a.Jc+b}function fa(a,b,c){var d=x(a,10),e=Math.round((b[0]-a.A.r)/d),f=Math.round((b[1]-a.A.s)/d);return null!=c?(c[0]=a.A.r+e*d,c[1]=a.A.s+f*d,c[2]=b[2],c):[a.A.r+e*d,a.A.s+f*d,b[2]]}
function ha(a){this.sb=1073741824;this.cc=402653184;this.Ha=4;this.Vb=45;this.Ta=6E5;this.za=180;this.ub=this.Ta;this.wb=-90;this.vb=-10;this.ya="aboveTerrainOnly";this.tb=this.za/5;this.dc=8;this.ec=32;this.gc=256;this.ra="./skydome.jpg";this.ka=[0.8,0.8,0.8];this.R="observer";if(null!=a&&(null!=a.cacheSize&&(this.sb=a.cacheSize),null!=a.gpuCacheSize&&(this.cc=a.gpuCacheSize),null!=a.numThreads&&(this.Ha=a.numThreads),null!=a.cameraFOV&&(this.Vb=a.cameraFOV),null!=a.cameraVisibility&&(this.Ta=a.cameraVisibility),
null!=a.cameraMinDistance&&(this.za=a.cameraMinDistance),null!=a.cameraMaxDistance&&(this.ub=a.cameraMaxDistance),null!=a.cameraMinTilt&&(this.wb=a.cameraMinTilt),null!=a.cameraMaxTilt&&(this.vb=a.cameraMaxTilt),null!=a.cameraConstrainMode&&(this.ya=a.cameraConstrainMode,this.tb=this.za/5),null!=a.gridEmbeddingFactor&&(this.dc=a.gridEmbeddingFactor),null!=a.gridMinTileSize&&(this.ec=a.gridMinTileSize),null!=a.skydomeTexture&&(this.ra=a.skydomeTexture),null!=a.hitTextureSize&&(this.gc=a.hitTextureSize),
null!=a.controlMode&&(this.R=a.controlMode),null!=a.controlInertia))for(var b=0;3>b;b++)this.ka[b]=a.controlInertia[b]};function ia(a,b,c,d,e,f){this.g=[];this.k=[];this.g[0]=null!=a?a:Number.POSITIVE_INFINITY;this.g[1]=null!=b?b:Number.POSITIVE_INFINITY;this.g[2]=null!=c?c:Number.POSITIVE_INFINITY;this.k[0]=null!=d?d:Number.NEGATIVE_INFINITY;this.k[1]=null!=e?e:Number.NEGATIVE_INFINITY;this.k[2]=null!=f?f:Number.NEGATIVE_INFINITY}function M(a,b){return a.k[b]-a.g[b]}function ja(a,b){return new ia(a.g[0]-b[0],a.g[1]-b[1],a.g[2],a.k[0]-b[0],a.k[1]-b[1],a.k[2])};function ka(a){this.oa=[];this.ab=null!=a?a:Number.MAX_VALUE;this.M=this.V=null;this.ha=0}h=ka.prototype;h.log=function(){for(var a=0,b=this.M;null!=b.aa&&!(b=this.oa[b.aa][3],a++,10<a););this.oa.forEach(function(){})};h.find=function(a){a=this.hash(a);a=this.oa[a];if(null!=a){if(this.M!=a){null!=a.ba&&(a.ba.aa=a.aa);null!=a.aa&&(a.aa.ba=a.ba);this.V==a&&(this.V=a.ba);var b=this.M;this.M=a;this.M.aa=b;this.M.ba=null;b.ba=this.M}return a.Za}return null};h.contains=function(a){return null!=this.oa[this.hash(a)]};
h.clear=function(){for(var a=this.M;null!=a;)null!=a.Za&&a.Za.v(),a=a.aa;this.oa=[];this.M=this.V=null;this.ha=0};function la(a,b,c,d){b=a.hash(b);c={Tc:b,Za:c,Lc:d,ba:null,aa:a.M};null!=a.M&&(a.M.ba=c);a.M=c;null==a.V&&(a.V=c);a.oa[b]=c;a.ha+=d;ma(a)}function ma(a){for(;a.ha>a.ab;){var b=a.V;if(null!=b)a.V=a.V.ba,null!=a.V&&(a.V.aa=null),a.oa[b.Tc]=null,a.ha-=b.Lc,b.Za.v();else break}}h.hash=function(a){return""+Math.round(a.l)+"."+Math.round(a.r)+"."+Math.round(a.s)};
function na(a,b,c,d,e){null==d&&(d=1);this.c=a;this.Ha=d;this.pb=0;this.F=new ka(b);this.qa=[];this.fb=[];this.ma=[];this.qc=c;this.Yb=e}h=na.prototype;h.get=function(a){var b=this.F.find(a);null==b&&this.Ib(a);return b};h.contains=function(a){return this.F.contains(a)};h.trim=function(a){var b=this.F.ab,c=this.F;c.ab=a;ma(c);a=this.F;a.ab=b;ma(a)};h.reset=function(){this.F.clear()};h.size=function(){return this.F.ha};
h.Ib=function(a){var b=this.F.hash(a),c=this.ma.indexOf(b);-1==c&&(c=this.qa.indexOf(b),-1!=c&&(this.qa.splice(c,1),this.fb.splice(c,1)),this.qa.unshift(b),this.fb.unshift(a),20<this.qa.length&&(this.qa.pop(),this.fb.pop()))};
h.update=function(){if(0<this.qa.length&&this.pb<this.Ha){var a=this.qa.shift(),b=this.fb.shift();if(-1==this.ma.indexOf(a)){this.ma.push(a);this.pb++;var a=function(a,b){this.ma.splice(this.ma.indexOf(this.F.hash(a)),1);this.pb--;la(this.F,a,b,b.size());null!=this.qc&&this.qc(a)}.bind(this),c=function(a){this.ma.splice(this.ma.indexOf(this.F.hash(a)),1);this.pb--}.bind(this);null!=this.Yb&&new this.Yb(this.c,b,a,c)}}};function oa(a,b,c,d){this.a=[0,0,0];this.f=[0,0,0];this.qb=1;this.ac=b;this.Hb=c;this.Aa=d;this.$=s.b.create();this.gb=s.b.create();this.eb=s.b.create();this.Y=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]];this.zc=[0,0,0,0];this.w=!0}h=oa.prototype;h.Na=function(a){this.a=a;this.w=!0};h.Ma=function(a){this.f=a;this.w=!0};h.ea=function(){return[this.a[0],this.a[1],this.a[2]]};h.Ab=function(){return[this.f[0],this.f[1],this.f[2]]};function pa(a){a.w&&a.update();return a.$}
function qa(a){a.w&&a.update();return a.gb}function ra(a){a.w&&a.update();return a.eb}function sa(a,b){a.w&&a.update();for(var c=[[b.g[0],b.g[1],b.g[2],1],[b.g[0],b.g[1],b.k[2],1],[b.g[0],b.k[1],b.g[2],1],[b.g[0],b.k[1],b.k[2],1],[b.k[0],b.g[1],b.g[2],1],[b.k[0],b.g[1],b.k[2],1],[b.k[0],b.k[1],b.g[2],1],[b.k[0],b.k[1],b.k[2],1]],d=0;6>d;d++){for(var e=!0,f=0;8>f;f++)if(0<=s.Sb.Xb(a.Y[d],c[f])){e=!1;break}if(e)return!1}return!0}
h.update=function(){this.$=s.b.create();s.b.multiply(s.La(1,s.X(-this.f[2])),s.La(0,s.X(-this.f[1]-90)),this.$);s.b.multiply(this.$,s.La(2,s.X(-this.f[0])),this.$);s.b.multiply(this.$,s.sa(-this.a[0],-this.a[1],-this.a[2]),this.$);this.gb=s.hd(this.ac,this.qb,this.Hb,this.Aa);this.eb=s.b.create();s.b.multiply(this.gb,this.$,this.eb);this.Y[0]=[0,0,1,1];this.Y[1]=[0,0,-1,1];this.Y[2]=[1,0,0,1];this.Y[3]=[-1,0,0,1];this.Y[4]=[0,1,0,1];this.Y[5]=[0,-1,0,1];var a=s.b.create();s.b.xa(this.eb,a);for(var b=
0;6>b;b++)this.Y[b]=s.b.cb(a,this.Y[b]);this.w=!1};s.Bc=function(a,b,c,d,e,f){var g=e.get(c);if(!g)return[d,c.l>=f];var k=x(a.p,c.l);d=(b[0]-c.r)/k;k=(b[1]-c.s)/k;d=s.ja(d,0,0.9999);var k=s.ja(k,0,0.9999),l=s.ia,m=d*(l-1),n=k*(l-1),p=Math.floor(m),q=Math.floor(n),r=g.S[q*l+p],t=g.S[(q+1)*l+p],m=m-p,r=r+(g.S[q*l+p+1]-r)*m,l=r+(t+(g.S[(q+1)*l+p+1]-t)*m-r)*(n-q),n=0,n=0.5>k?0.5>d?0:1:0.5>d?2:3;return!(g.T&1<<n)||c.l>=f?[l,!0]:s.Bc(a,b,N(c,n),l,e)};s.Ra=function(a,b,c){var d;null==d&&(d=Number.MAX_VALUE);return s.Bc(a,b,a.p.A,0,c,d)};function O(a,b){this.J=a;this.C=null;this.n=b;this.Wb=null}function ta(a){a.C=document.createElement("canvas");if(null!=a.C&&(a.C.width=a.n[0],a.C.height=a.n[1],a.C.style.display="block",null!=a.C.getContext)){try{a.e=a.C.getContext("webgl")||a.C.getContext("experimental-webgl")}catch(b){}a.e&&(a.J.appendChild(a.C),a.e.Ub=a.C.width,a.e.Tb=a.C.height,a.e.clearColor(0,0,0,1),a.e.enable(a.e.DEPTH_TEST),a.e.viewport(0,0,a.e.Ub,a.e.Tb),a.e.clear(a.e.COLOR_BUFFER_BIT|a.e.DEPTH_BUFFER_BIT))}}
O.prototype.resize=function(a,b){this.n=a;null!=this.C&&!0!=b&&(this.C.width=this.n[0],this.C.height=this.n[1]);null!=this.e&&(this.e.Ub=this.C.width,this.e.Tb=this.C.height)};O.prototype.clear=function(){this.e.clear(this.e.DEPTH_BUFFER_BIT);this.e.enable(this.e.CULL_FACE)};O.prototype.useProgram=function(a,b,c){this.Wb!=a&&(this.e.useProgram(a.W),this.Wb=a,ua(a),b=a.getAttribute(b),this.e.enableVertexAttribArray(b),null!=c&&(a=a.getAttribute(c),this.e.enableVertexAttribArray(a)))};
O.prototype.bindTexture=function(a){!1!=a.Fb&&(this.e.activeTexture(this.e.TEXTURE0),this.e.bindTexture(this.e.TEXTURE_2D,a.H))};s.Dd=function(){return!0};function P(a,b){null!=b?a.e.bindFramebuffer(a.e.FRAMEBUFFER,b.bc):(a.e.bindTexture(a.e.TEXTURE_2D,null),a.e.bindRenderbuffer(a.e.RENDERBUFFER,null),a.e.bindFramebuffer(a.e.FRAMEBUFFER,null))};function Q(a,b,c){this.j=b.j;this.e=a.e;this.Xa=c;a=this.e;null!=a&&(this.ta=this.da=null,this.da=a.createBuffer(),a.bindBuffer(a.ARRAY_BUFFER,this.da),a.bufferData(a.ARRAY_BUFFER,new Float32Array(b.q),a.STATIC_DRAW),this.da.Fa=3,this.da.Ga=b.q.length/3,this.ta=a.createBuffer(),a.bindBuffer(a.ARRAY_BUFFER,this.ta),a.bufferData(a.ARRAY_BUFFER,new Float32Array(b.t),a.STATIC_DRAW),this.ta.Fa=2,this.ta.Ga=b.t.length/2,this.Q=4*(b.q.length+b.t.length)+32,this.Jb=this.da.Ga/3)}
Q.prototype.v=function(){this.e.deleteBuffer(this.da);this.e.deleteBuffer(this.ta)};function va(a,b){var c=a.e;if(null!=c){var d=b.getAttribute("aPosition"),e=b.getAttribute("aTexCoord");c.bindBuffer(c.ARRAY_BUFFER,a.da);c.vertexAttribPointer(d,a.da.Fa,c.FLOAT,!1,0,0);c.bindBuffer(c.ARRAY_BUFFER,a.ta);c.vertexAttribPointer(e,a.ta.Fa,c.FLOAT,!1,0,0);c.drawArrays(c.TRIANGLES,0,a.da.Ga)}}Q.prototype.size=function(){return this.Q};function R(a,b,c){this.e=a.e;this.W=null;this.Pb=[];this.rb=[];this.createProgram(b,c)}R.prototype.createShader=function(a,b){if(!a)return null;var c=this.e;if(null!=c){var d;d=!0!=b?c.createShader(c.FRAGMENT_SHADER):c.createShader(c.VERTEX_SHADER);c.shaderSource(d,a);c.compileShader(d);return c.getShaderParameter(d,c.COMPILE_STATUS)?d:(alert("An error occurred compiling the shaders: "+c.getShaderInfoLog(d)),null)}};
R.prototype.createProgram=function(a,b){var c=this.e;if(null!=c){var d=this.createShader(a,!0),e=this.createShader(b,!1),f=c.createProgram();c.attachShader(f,d);c.attachShader(f,e);c.linkProgram(f);c.getProgramParameter(f,c.LINK_STATUS)||alert("Unable to initialize the shader program.");c.useProgram(f);this.W=f}};function ua(a){var b=a.e;null!=b&&null!=a.W&&(a=a.getUniform("uSampler"),null!=a&&b.uniform1i(a,0))}
function S(a,b,c){var d=a.e;null!=d&&null!=a.W&&(a=a.getUniform(b),null!=a&&d.uniformMatrix4fv(a,!1,c))}function T(a,b,c){var d=a.e;null!=d&&null!=a.W&&(a=a.getUniform(b),null!=a&&d.uniform1f(a,c))}R.prototype.getAttribute=function(a){var b=this.e;if(null!=b&&null!=this.W)return null==this.rb[a]?(b=b.getAttribLocation(this.W,a),this.rb[a]=b):this.rb[a]};
R.prototype.getUniform=function(a){var b=this.e;if(null!=b&&null!=this.W)return null==this.Pb[a]?(b=b.getUniformLocation(this.W,a),this.Pb[a]=b):this.Pb[a]};s.ud="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMVP;\nvarying vec2 vTexCoord;\nvoid main(){ \ngl_Position = uMVP * vec4(aPosition, 1.0);\nvTexCoord = aTexCoord;\n}";s.td="precision mediump float;\nuniform sampler2D uSampler;\nvarying vec2 vTexCoord;\nconst vec4 gray = vec4(0.125, 0.125, 0.125, 1.0);\nvoid main() {\nfloat fade = smoothstep(0.51, 0.55, vTexCoord.t);\ngl_FragColor = mix(texture2D(uSampler, vTexCoord), gray, fade);\n}";s.Yc="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nuniform mat4 uGridMat;\nuniform float uGridStep1, uGridStep2;\nconst int HMSize = 5;\nconst float HMSize1 = float(HMSize-1);\nuniform float uHeight[HMSize*HMSize];\nvarying vec2 vTexCoord1;\nvarying vec2 vTexCoord2;\nvarying float vFogFactor;\nfloat round(float x) { return floor(x + 0.5); }\nvoid main() {\nvec3 pos = aPosition;\nfloat z = uHeight[int(round(pos.y*HMSize1)*float(HMSize) + round(pos.x*HMSize1))];\nvec4 camSpacePos = uMV * vec4(pos.xy, z, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvFogFactor = exp(uFogDensity * camDist);\nvec4 gridCoord = uGridMat * vec4(pos, 1.0);\nvTexCoord1 = aTexCoord;\nvTexCoord1 = gridCoord.xy * vec2(uGridStep1);\nvTexCoord2 = gridCoord.xy * vec2(uGridStep2);\n}";
s.Wc="precision mediump float;\nuniform sampler2D uSampler;\nuniform float uGridBlend;\nvarying vec2 vTexCoord1;\nvarying vec2 vTexCoord2;\nvarying float vFogFactor;\nconst vec4 fogColor = vec4(1, 1, 1, 1);\nvoid main() {\nvec4 gridColor = mix(texture2D(uSampler, vTexCoord1), texture2D(uSampler, vTexCoord2), uGridBlend);\ngl_FragColor = mix(fogColor, gridColor, vFogFactor);\n}";s.Vc="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nuniform mat4 uGridMat;\nuniform float uGridStep1, uGridStep2;\nconst int HMSize = 5;\nconst float HMSize1 = float(HMSize-1);\nuniform float uHeight[HMSize*HMSize];\nvarying vec2 vTexCoord1;\nvarying vec2 vTexCoord2;\nvarying float vDepth;\nfloat round(float x) { return floor(x + 0.5); }\nvoid main() {\nvec3 pos = aPosition;\nfloat z = uHeight[int(round(pos.y*HMSize1)*float(HMSize) + round(pos.x*HMSize1))];\nvec4 camSpacePos = uMV * vec4(pos.xy, z, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvDepth = camDist;\nvec4 gridCoord = uGridMat * vec4(pos, 1.0);\nvTexCoord1 = aTexCoord;\nvTexCoord1 = gridCoord.xy * vec2(uGridStep1);\nvTexCoord2 = gridCoord.xy * vec2(uGridStep2);\n}";
s.Uc="precision mediump float;\nuniform sampler2D uSampler;\nuniform float uGridBlend;\nvarying vec2 vTexCoord1;\nvarying vec2 vTexCoord2;\nvarying float vDepth;\nconst vec4 fogColor = vec4(1, 1, 1, 1);\nvoid main() {\ngl_FragColor = fract(vec4(1.0, 1.0/255.0, 1.0/65025.0, 1.0/16581375.0) * vDepth) + (-0.5/255.0);\n}";s.yd="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nvarying vec2 vTexCoord;\nvarying float vFogFactor;\nvoid main() {\nvec4 camSpacePos = uMV * vec4(aPosition, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvFogFactor = exp(uFogDensity * camDist);\nvTexCoord = aTexCoord;\n}";
s.xd="precision mediump float;\nuniform sampler2D uSampler;\nvarying vec2 vTexCoord;\nvarying float vFogFactor;\nconst vec4 fogColor = vec4(1, 1, 1, 1);\nvoid main() {\ngl_FragColor = mix(fogColor, texture2D(uSampler, vTexCoord), vFogFactor);\n}";s.wd="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nvarying vec2 vTexCoord;\nvarying float vDepth;\nvoid main() {\nvec4 camSpacePos = uMV * vec4(aPosition, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvDepth = camDist;\nvTexCoord = aTexCoord;\n}";
s.vd="precision mediump float;\nuniform sampler2D uSampler;\nvarying float vDepth;\nvoid main() {\ngl_FragColor = fract(vec4(1.0, 1.0/255.0, 1.0/65025.0, 1.0/16581375.0) * vDepth) + (-0.5/255.0);\n}";s.$c="\nattribute vec4 aPosition;\nuniform mat4 uProjectionMatrix;\nuniform mat4 uData;\nuniform vec4 uColor;\nvarying vec4 vColor;\nvarying vec2 vTexcoords;\nvoid main(void){\nint i=int(aPosition.x);\nif(i==0) gl_Position=uProjectionMatrix*vec4(floor(uData[0][0]+0.1),floor(uData[0][1]+0.1),0.0,1.0), vTexcoords=vec2(uData[0][2], uData[0][3]);\nif(i==1) gl_Position=uProjectionMatrix*vec4(floor(uData[1][0]+0.1),floor(uData[1][1]+0.1),0.0,1.0), vTexcoords=vec2(uData[1][2], uData[1][3]);\nif(i==2) gl_Position=uProjectionMatrix*vec4(floor(uData[2][0]+0.1),floor(uData[2][1]+0.1),0.0,1.0), vTexcoords=vec2(uData[2][2], uData[2][3]);\nif(i==3) gl_Position=uProjectionMatrix*vec4(floor(uData[3][0]+0.1),floor(uData[3][1]+0.1),0.0,1.0), vTexcoords=vec2(uData[3][2], uData[3][3]);\nvec4 c=uColor*(1.0/255.0);\nc.w*=1.0;\nvColor=c;\n}";
s.Zc="precision mediump float;\nvarying vec4 vColor;\nvarying vec2 vTexcoords;\nuniform sampler2D uSampler;\nvoid main(void){\nvec4 c=texture2D(uSampler, vec2(vTexcoords.x, 1.0-vTexcoords.y) );\nc*=vColor;\ngl_FragColor = c;\n}";function U(a,b,c,d){this.i=a;this.e=a.e;this.bc=this.H=null;this.Q=0;this.Xa=d;this.G=null;this.Fb=!1;this.c=c;null!=b&&this.load(b)}U.prototype.v=function(){this.e.deleteTexture(this.H)};U.prototype.size=function(){return this.Q};
function wa(a,b,c,d,e,f){var g=a.e;a.H=g.createTexture();g.bindTexture(g.TEXTURE_2D,a.H);f=!0==f?g.REPEAT:g.CLAMP_TO_EDGE;g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,f);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,f);f=!1;switch(e){case "linear":g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);break;case "trilinear":g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR_MIPMAP_LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,
g.LINEAR);f=!0;break;default:g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST),g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.NEAREST)}g.pixelStorei(g.UNPACK_ALIGNMENT,1);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,b,c,0,g.RGBA,g.UNSIGNED_BYTE,d);!0==f&&g.generateMipmap(g.TEXTURE_2D);g.bindTexture(g.TEXTURE_2D,null);a.Q=b*c*4;a.Fb=!0}
function xa(a,b,c){var d=a.e;a.H=d.createTexture();d.bindTexture(d.TEXTURE_2D,a.H);c=!0==c?d.REPEAT:d.CLAMP_TO_EDGE;d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_S,c);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_T,c);c=!1;switch("linear"){case "linear":d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.LINEAR);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MAG_FILTER,d.LINEAR);break;case "trilinear":d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.LINEAR_MIPMAP_LINEAR);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MAG_FILTER,
d.LINEAR);c=!0;break;default:d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.NEAREST),d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MAG_FILTER,d.NEAREST)}d.texImage2D(d.TEXTURE_2D,0,d.RGBA,d.RGBA,d.UNSIGNED_BYTE,b);!0==c&&d.generateMipmap(d.TEXTURE_2D);d.bindTexture(d.TEXTURE_2D,null);a.Q=b.naturalWidth*b.naturalHeight*4;a.Fb=!0}
U.prototype.load=function(a,b,c){this.G=new Image;this.G.crossOrigin="anonymous";this.G.onload=function(){if(null==this.c||!0!=this.c.o)xa(this,this.G,!1),this.G=null}.bind(this);this.G.onerror=function(){null!=this.c&&!0==this.c.o||null==c||c()}.bind(this);this.G.src=a};
U.prototype.createFramebuffer=function(a,b){if(null!=this.H){var c=this.e,d=c.createFramebuffer();c.bindFramebuffer(c.FRAMEBUFFER,d);d.width=a;d.height=b;c.bindTexture(c.TEXTURE_2D,this.H);var e=c.createRenderbuffer();c.bindRenderbuffer(c.RENDERBUFFER,e);c.renderbufferStorage(c.RENDERBUFFER,c.DEPTH_COMPONENT16,a,b);c.framebufferTexture2D(c.FRAMEBUFFER,c.COLOR_ATTACHMENT0,c.TEXTURE_2D,this.H,0);c.framebufferRenderbuffer(c.FRAMEBUFFER,c.DEPTH_ATTACHMENT,c.RENDERBUFFER,e);c.bindTexture(c.TEXTURE_2D,
null);c.bindRenderbuffer(c.RENDERBUFFER,null);c.bindFramebuffer(c.FRAMEBUFFER,null);this.bc=d}};function ya(a,b){this.i=a;this.K=new Q(a,b.K);this.H=new U(a);xa(this.H,b.G);this.Gb=b.Gb;this.Db=b.Db}ya.prototype.v=function(){this.K.v();this.H.v()};ya.prototype.size=function(){return this.K.size()+this.H.size()};function za(a,b){this.i=a;this.F=new ka(b)}za.prototype.get=function(a,b){var c=this.F.find(a);if(c)return c;c=new ya(this.i,b);la(this.F,a,c,c.size());return c};za.prototype.size=function(){return this.F.ha};za.prototype.reset=function(){return this.F.clear()};function V(){this.q=[];this.t=[];this.j=new ia;this.Xa=this.Q=0}V.prototype.v=function(){this.q=[];this.t=[];this.j=null};
V.prototype.load=function(a,b,c){s.jc(a,function(a){this.Xa=a.byteLength;for(var c=0,f=1/65535,g="",k=0;8>k;k++)g+=String.fromCharCode(a.getUint8(c,!0)),c+=1;if("BIN.MESH"==g&&(k=a.getUint32(c,!0),c+=4,!(1<k))){for(k=0;3>k;k++)this.j.g[k]=a.getFloat64(c,!0),c+=8;for(k=0;3>k;k++)this.j.k[k]=a.getFloat64(c,!0),c+=8;for(var g=a.getUint16(c,!0),c=c+2,l=Array(3*g),m=0;m<g;m++)k=3*m,l[k]=a.getUint16(c,!0),c+=2,l[k+1]=a.getUint16(c,!0),c+=2,l[k+2]=a.getUint16(c,!0),c+=2;for(var g=a.getUint16(c,!0),c=c+2,
n=Array(2*g),m=0;m<g;m++)k=2*m,n[k]=a.getUint16(c,!0),c+=2,n[k+1]=65535-a.getUint16(c,!0),c+=2;g=a.getUint16(c,!0);c+=2;this.q=Array(9*g);this.t=Array(6*g);for(m=0;m<g;m++){for(k=0;3>k;k++){var p=3*a.getUint16(c,!0),c=c+2,q=9*m+3*k;this.q[q]=l[p]*f;this.q[q+1]=l[p+1]*f;this.q[q+2]=l[p+2]*f}for(k=0;3>k;k++)p=2*a.getUint16(c,!0),c+=2,q=6*m+2*k,this.t[q]=n[p]*f,this.t[q+1]=n[p+1]*f}this.Q=8*(this.q.length+this.t.length)+56;null!=b&&b()}}.bind(this),function(){null!=c&&c()}.bind(this))};
V.prototype.size=function(){return this.Q};V.prototype.fileSize=function(){return this.Xa};s.nb=function(a,b){b*=Math.PI;a=2*a*Math.PI;return[Math.cos(a)*Math.sin(b)*0.5+0.5,Math.sin(a)*Math.sin(b)*0.5+0.5,0.5*Math.cos(b)+0.5]};s.ia=5;function Aa(a,b,c){this.c=a;this.j=new ia;this.va=[];this.S=[];this.T=0;this.Pa=[];for(a=0;2>a;a++)this.va[a]=[];var d=c.la.getInt16(c.u,!0);c.u+=2;a=c.la.getInt16(c.u,!0);c.u+=2;this.j.g[0]=b.r;this.j.g[1]=b.s;this.j.g[2]=d;d=x(this.c.p,b.l);this.j.k[0]=b.r+d;this.j.k[1]=b.s+d;this.j.k[2]=a;for(a=0;2>a;a++)for(b=0;2>b;b++)this.va[a][b]=c.la.getFloat32(c.u,!0),c.u+=4;a=0;for(b=s.ia*s.ia;a<b;a++)this.S[a]=c.la.getInt16(c.u,!0),c.u+=2;for(a=0;4>a;a++)this.Pa[a]=null;this.T=0}
Aa.prototype.Ba=function(a,b){var c=b;null!=c?(c[0]=M(this.j,0),c[1]=0,c[2]=0,c[3]=0,c[4]=0,c[5]=M(this.j,1),c[6]=0,c[7]=0,c[8]=0,c[9]=0,c[10]=1,c[11]=0,c[12]=this.j.g[0]-a[0],c[13]=this.j.g[1]-a[1],c[14]=0,c[15]=1):(c=s.b.create(),s.b.multiply(s.sa(this.j.g[0]-a[0],this.j.g[1]-a[1],0),s.mb(M(this.j,0),M(this.j,1),1),c));return c};Aa.prototype.size=function(){for(var a=308,b=0;4>b;b++)null!=this.Pa[b]&&(a+=this.Pa[b].size());return a};
function Ba(a,b,c){this.B=b;this.c=a;a="";for(var d=0;8>d;d++)a+=String.fromCharCode(c.la.getUint8(c.u,!0)),c.u+=1;"METATILE"==a&&(a=c.la.getUint32(c.u,!0),c.u+=4,1<a||(this.Dc=Ca(this,b,c)))}Ba.prototype.v=function(){};function Ca(a,b,c){var d=new Aa(a.c,b,c),e=c.la.getUint8(c.u,!0);c.u+=1;for(var f=0;4>f;f++)e&1<<f+4&&(d.Pa[f]=Ca(a,N(b,f),c));d.T=e&15;return d}Ba.prototype.size=function(){return this.Dc.size()};
s.Gc=function(a,b,c,d){this.c=a;this.B=b;this.Ja=c;this.Ia=d;this.cd=function(b){!0!=this.c.o&&null!=this.Ja&&(b=new Ba(a,this.B,{la:b,u:0}),this.Ja(this.B,b))}.bind(this);this.bd=function(){!0!=this.c.o&&null!=this.Ia&&this.Ia(this.B)}.bind(this);s.jc(ba(this.c.p,this.B),this.cd,this.bd)};
function Da(a,b,c,d,e){this.c=a;this.L=new na(a,b,c,d,e);this.contains=this.L.contains.bind(this.L);this.trim=this.L.trim.bind(this.L);this.reset=this.L.reset.bind(this.L);this.Ib=this.L.Ib.bind(this.L);this.update=this.L.update.bind(this.L);this.size=this.L.size.bind(this.L)}
Da.prototype.get=function(a){for(var b=a,c=this.c.p;Math.abs(b.l-c.oc)%c.nc&&b.l>c.A.l;)b=b.parent();if(b=this.L.get(b)){for(var c=new u(b.c,b.B.l,b.B.r,b.B.s),d=b.Dc;c.l<a.l;){var e=x(b.c.p,c.l),f=c.r+e/2,e=c.s+e/2,g=0;Math.round(a.r)>=Math.round(f)&&(g|=1,c.r=f);Math.round(a.s)>=Math.round(e)&&(g|=2,c.s=e);c.l++;(d=d.Pa[g])||console.log("Missing tile metadata")}!c.isEqual(a)&&console.log("Metatile inconsistency");a=d}else a=null;return a};s.Nb=1.1;
function Ea(a,b,c){this.c=a;this.Ka=this.uc=this.vc=null;this.J=b;this.sc=c;this.pa=this.o=!1;this.n=[b.clientWidth,b.clientHeight];this.Sa=!1;this.w=this.fc=!0;this.ad=1;this.i=new O(b,this.n);this.h=new oa(0,this.c.m.Vb,20,this.c.m.Ta);this.a=[this.c.p.Wa[0],this.c.p.Wa[1],this.c.p.Wa[2]];this.f=[this.c.p.Va[0],this.c.p.Va[1],this.c.p.Va[2]];this.O=new Da(this.c,Number.MAX_VALUE,function(){this.w=!0}.bind(this),this.c.m.Ha,s.Gc);this.ca=new s.Hc(this.c,Number.MAX_VALUE,function(){this.w=!0}.bind(this),
this.c.m.Ha,s.Ic);this.Bb=new za(this.i,this.c.m.cc);this.ra=this.Oa=this.Da=this.Ca=null;this.Xc=!1;this.na=null;this.Ea=this.c.m.gc;this.Rb=!0;this.hb=this.ib=this.wc=null;this.Fc=!0;this.Ac=document.getElementById("renderStats");this.lb=this.xc=this.fa=this.Lb=this.Mb=this.ob=this.Qa=0;this.wa=[];this.jb=this.kb=0;this.Eb=null;this.zb=0;this.$b=s.b.create();this.Zb=s.b.create();this.Mc=[0,0,0];this.Nc=s.b.create();this.jd=s.b.create();this.Ec=s.b.create();this.nd=[0,0,0];this.md=[[3,1,2,0],[3,
2,1,0],[2,3,0,1],[2,0,3,1],[0,2,1,3],[0,1,2,3],[1,0,3,2],[1,3,0,2]];this.$a=[0,0,100];window.addEventListener("resize",this.rc.bind(this),false);ta(this.i);this.vc=new R(this.i,s.yd,s.xd);this.uc=new R(this.i,s.Yc,s.Wc);this.Ka=new R(this.i,s.ud,s.td);this.ld=new R(this.i,s.wd,s.vd);this.kd=new R(this.i,s.Vc,s.Uc);new R(this.i,s.$c,s.Zc);Fa(this);Ga(this);Ha(this);Ia(this);Ja(this,this.n[0],this.n[1]);window.yc(this.update.bind(this))}h=Ea.prototype;
h.rc=function(){!0!=this.o&&Ja(this,this.J.clientWidth,this.J.clientHeight)};h.v=function(){!0!=this.o&&(this.o=!0,this.O.reset(),this.ca.reset(),this.Bb.reset(),null!=this.Ca&&this.Ca.v(),null!=this.Da&&this.Da.v(),null!=this.Oa&&this.Oa.v(),null!=this.ra&&this.ra.v(),null!=this.na&&this.na.v(),this.J.removeChild(this.i.C))};
function Fa(a){var b=new V,c=s.ia;c--;for(var d=0;d<c;d++)for(var e=0;e<c;e++){var f=e/c,g=(e+1)/c,k=d/c,l=(d+1)/c;b.q.push(f,k,0);b.q.push(g,k,0);b.q.push(g,l,0);b.t.push(f,k);b.t.push(g,k);b.t.push(g,l);b.q.push(g,l,0);b.q.push(f,l,0);b.q.push(f,k,0);b.t.push(g,l);b.t.push(f,l);b.t.push(f,k)}b.j.g[0]=b.j.g[1]=b.j.g[2]=0;b.j.k[0]=b.j.k[1]=b.j.k[2]=1;b.Q=8*(b.q.length+b.t.length)+56;a.Ca=new Q(a.i,b);b=new Uint8Array(16384);for(c=0;64>c;c++)for(d=0;64>d;d++)e=4*(64*c+d),1>c||63<=c||1>d||63<=d?(b[e]=
255,b[e+1]=255,b[e+2]=255):(b[e]=32,b[e+1]=32,b[e+2]=32),b[e+3]=255;a.Da=new U(a.i);wa(a.Da,64,64,b,"trilinear",!0)}function Ha(a){var b=a.Ea,c=new Uint8Array(b*b*4);a.na=new U(a.i);wa(a.na,b,b,c);a.na.createFramebuffer(b,b);for(var b=16,c=new Uint8Array(b*b*4),d=0;d<b;d++)for(var e=0;e<b;e++){var f=4*(d*b+e);c[f]=255;c[f+1]=0;c[f+2]=0;c[f+3]=255}a.wc=new U(a.i);wa(a.wc,b,b,c)}
function Ia(a){var b=a.i.e;a.ib=b.createBuffer();b.bindBuffer(b.ARRAY_BUFFER,a.ib);b.bufferData(b.ARRAY_BUFFER,new Float32Array([0,0,0,1,1,0,0,1,2,0,0,1,3,0,0,1]),b.STATIC_DRAW);a.ib.Fa=4;a.ib.Ga=4;a.hb=b.createBuffer();b.bindBuffer(b.ELEMENT_ARRAY_BUFFER,a.hb);b.bufferData(b.ELEMENT_ARRAY_BUFFER,new Uint16Array([0,1,2,0,2,3]),b.STATIC_DRAW);a.hb.Fa=1;a.hb.Ga=6}
function Ga(a){for(var b=new V,c=0;32>c;c++)for(var d=0;64>d;d++){var e=b,f=d/64,g=c/32,k=(d+1)/64,l=(c+1)/32,m=s.nb(f,g),n=[f,g],p=s.nb(f,l),f=[f,l],q=s.nb(k,g),g=[k,g],r=s.nb(k,l),k=[k,l];e.q.push(p[0],p[1],p[2]);e.q.push(m[0],m[1],m[2]);e.q.push(q[0],q[1],q[2]);e.t.push(f[0],f[1]);e.t.push(n[0],n[1]);e.t.push(g[0],g[1]);e.q.push(q[0],q[1],q[2]);e.q.push(r[0],r[1],r[2]);e.q.push(p[0],p[1],p[2]);e.t.push(g[0],g[1]);e.t.push(k[0],k[1]);e.t.push(f[0],f[1]);e.Q=8*(e.q.length+e.t.length)+56}b.j.g[0]=
b.j.g[1]=b.j.g[2]=0;b.j.k[0]=b.j.k[1]=b.j.k[2]=1;a.Oa=new Q(a.i,b);a.ra=new U(a.i,a.c.m.ra,a.c)}function Ja(a,b,c){var d=a.h;d.qb=b/c;d.w=!0;a.n=[b,c];a.i.resize(a.n,void 0);Ka(a)}function La(a,b){var c=Math.log(0.05)/(10*a.c.m.Ta*(Math.max(5,-a.f[1])/90));T(b,"uFogDensity",c)}
function Ma(a,b,c,d){null==a.wa[b.l]?a.wa[b.l]=1:a.wa[b.l]++;if(c&&!a.Xc){a.kb+=c.Gb;a.jb+=c.Db;d=a.Bb.get(b,c);b=!0==a.pa?a.ld:a.vc;a.i.useProgram(b,"aPosition","aTexCoord");var e=a.$b;s.b.multiply(pa(a.h),c.Ba(a.a,a.Nc),e);c=qa(a.h);S(b,"uMV",e);S(b,"uProj",c);La(a,b);a.i.bindTexture(d.H);va(d.K,b);!0!=a.pa&&(a.Mb++,a.fa+=d.K.Jb)}else{b=!0==a.pa?a.kd:a.uc;a.i.useProgram(b,"aPosition","aTexCoord");e=a.$b;s.b.multiply(pa(a.h),d.Ba(a.a,a.Zb),e);S(b,"uMV",e);S(b,"uProj",qa(a.h));c=a.Zb;d.Ba(fa(a.c.p,
a.a,a.Mc),c);S(b,"uGridMat",c);La(a,b);c=a.c.m.dc;var e=a.c.m.ec,f=s.ia,f=Math.log(a.h.a[2]-0.25*(d.S[0]+d.S[f-1]+d.S[(f-1)*f]+d.S[(f-1)*f+f-1])+20)/Math.log(c),g=Math.pow(c,Math.ceil(f)),k=f-Math.floor(f);T(b,"uGridStep1",e/Math.pow(c,Math.floor(f)));T(b,"uGridStep2",e/g);T(b,"uGridBlend",k);d=d.S;c=b.e;null!=c&&null!=b.W&&(e=b.getUniform("uHeight"),null!=e&&c.uniform1fv(e,d));a.i.bindTexture(a.Da);va(a.Ca,b);!0!=a.pa&&(a.Lb++,a.fa+=a.Ca.Jb)}}
function Na(a){var b=s.b.create();s.b.multiply(s.mb(2,2,2),s.sa(-0.5,-0.5,-0.5),b);var c=s.b.create();s.b.multiply(s.sa(a.h.ea()[0],a.h.ea()[1],a.h.ea()[2]-400),s.od(0.9*a.h.Aa),c);var d=s.b.create();s.b.multiply(ra(a.h),c,d);s.b.multiply(d,b,d);a.i.useProgram(a.Ka,"aPosition","aTexCoord");a.i.bindTexture(a.ra);ua(a.Ka);S(a.Ka,"uMVP",d);va(a.Oa,a.Ka);a.fa+=a.Oa.Jb}
function Oa(a,b){for(var c=b.Ba(a.a,a.jd),d=a.n[0]/2,e=0,f=s.ia,g=s.ia-1,k=0;1>=k;k++)for(var l=0;1>=l;l++){var m=[];s.b.bb(c,[l,k,b.S[k*g*f+l*g]],m);var n=a.h;n.w&&n.update();s.b.bb(n.$,m,n.zc);m=s.I.length(n.zc);n=(m<n.Hb?Number.POSITIVE_INFINITY:n.gb[0]/m)*b.va[k][l]*d;n>e&&(e=n)}return e}
function Pa(a,b){var c=a.O.get(b);if(!c||!sa(a.h,ja(c.j,a.a)))return 0;if(!(1E6>c.va[0][0]))return Qa(a,b,c);var d=Oa(a,c);if(!c.T||d<s.Nb*a.ad){var e=a.ca.get(b),f;if(!(f=e)){a:{if(c.T)for(f=0;4>f;f++)if(c.T&1<<f&&a.ca.contains(N(b,f))){f=!0;break a}f=!1}f=!f}f?Ma(a,b,e,c):Qa(a,b,c);return d}if(d=2.2>d)a:{if(a.ca.contains(b)&&1E6>c.va[0][0])for(d=0;4>d;d++)if(c.T&1<<d&&(f=N(b,d),e=a.ca.get(f),f=a.O.get(f),!e||!f)){d=!0;break a}d=!1}return d?(e=a.ca.get(b),Ma(a,b,e,c),0):Qa(a,b,c)}
function Qa(a,b,c){var d=a.md,e;e=c.j;var f=a.nd;null!=f?(f[0]=0.5*(e.g[0]+e.k[0]),f[1]=0.5*(e.g[1]+e.k[1]),e=f):e=[0.5*(e.g[0]+e.k[0]),0.5*(e.g[1]+e.k[1]),0.5*(e.g[2]+e.k[2])];f=a.h.a;e=Math.floor((Math.atan2(a.a[1]+f[1]-e[1],a.a[0]+f[0]-e[0])+Math.PI)/Math.PI*4);e=s.ja(e,0,7);for(var g=f=0;4>g;g++){var k=d[e][g];c.T&1<<k&&(f=Math.max(f,Pa(a,N(b,k))))}return f}
function Ra(a,b){var c=a.O.get(b);if(!c||!sa(a.h,ja(c.j,a.a)))return 0;if(1E6>c.va[0][0]){var d=Oa(a,c);if(!c.T||d<s.Nb)return d}for(var e=d=0;4>e;e++)c.T&1<<e&&(d=Math.max(d,Ra(a,N(b,e))));return d}
function W(a){switch(a.c.m.R){case "observer":a.f[1]=s.ja(a.f[1],-90,10);a.a[2]=s.ja(a.a[2],5,a.h.Aa);s.b.multiply(s.La(2,s.X(a.f[0])),s.La(0,s.X(a.f[1])),a.Ec);var b=[0,-a.a[2],0];s.b.bb(a.Ec,b);b[2]+=s.Ra(a.c,a.a,a.O)[0];a.h.Na(b);a.h.Ma(a.f);break;case "drone":a.f[1]=s.ja(a.f[1],-90,90);a.a[2]=s.ja(a.a[2],5,a.h.Aa);b=a.h.a;a.h.Na([0,0,a.a[2]+s.Ra(a.c,[a.a[0]+b[0],a.a[1]+b[1]],a.O)[0]]);a.h.Ma(a.f);break;case "manual":a.h.Na([0,0,a.a[2]]),a.h.Ma(a.f)}a.w=!0}
function Z(a){var b=a.h.a;return a.h.ea()[2]-s.Ra(a.c,[a.a[0]+b[0],a.a[1]+b[1]],a.O)[0]}function Sa(a){var b=a.h.ea();b[0]+=a.a[0];b[1]+=a.a[1];return b}
function Ta(a){var b=a.c.m;if("manual"==b.R)return!1;var c=Math.max(b.tb,20/b.tb*a.a[2]*0.1);if(Z(a)<c){if(a.a[2]<c){var d=function(a,b,e){var l=0.5*(a+b);if(20<e)return l;this.a[2]=l;W(this);return Z(this)<c?d(a,l,e+1):d(l,b,e+1)}.bind(a);a.a[2]=d(a.a[2]+250,a.a[2],0)}else{var e=function(a,b,d){var l=0.5*(a+b);if(20<d)return l;this.f[1]=l;W(this);return Z(this)<c?e(a,l,d+1):e(l,b,d+1)}.bind(a);a.f[1]=e(-89,Math.min(-1,a.f[1]),0)}W(a)}return!1}
function Ua(a){if("manual"==a.c.m.R)return!1;var b=1E3,c=20,c=Math.max(20,0.1*a.a[2]);if(a.Sa||-10<a.f[1]){var d=function(a,b,g){var k=0.5*(a+b);if(20<g)return k;this.f[1]=k;W(this);return Z(this)<c?d(a,k,g+1):d(k,b,g+1)}.bind(a);Z(a)<c&&(a.f[1]=d(-89,Math.min(-1,a.f[1]),0),W(a))}else for(;Z(a)<c&&0<b;)a.a[2]+=0.01,W(a),b--;return!1}
function Va(a){var b=a.c.m;if("manual"==b.R)return!1;switch(b.ya){case "aboveTerrainOnly":return Ta(a);case "aboveTerrainOnlyOld":return Ua(a);default:for(var c,b=!1,d=a.c.m,e=1E3;(c>s.Nb||0>Z(a))&&0<e;){b=!0;if("observer"==d.R)if(a.Sa||-10<a.f[1])250>a.a[2]?a.a[2]+=0.3:a.f[1]-=0.3;else{var f=s.X(a.f[0]),g=s.X(-a.f[1]);c=0.5/Math.sin(g);g=c*Math.cos(g);f=[-Math.sin(f),Math.cos(f),0];a.a[0]+=g*f[0];a.a[1]+=g*f[1];a.a[2]+=c}else a.a[2]+=0.5;W(a);c=Ra(a,a.c.p.A);e--}return b}}
function Ka(a,b){a.pa=null!=b?b:!1;var c=a.c.m;if("drone"==c.R&&!a.fc){var d=s.Ra(a.c,a.a,a.O);if(!d[1])return;a.a[2]+=d[0];a.fc=!0}var e=!1,d=a.c.m;if("observer"==d.R){if(a.a[2]<d.za){a.a[2]=d.za;var e=s.X(a.f[0]),f=s.X(-a.f[1]),f=0.5/Math.sin(f)*Math.cos(f),e=[-Math.sin(e),Math.cos(e),0];a.a[0]+=f*e[0];a.a[1]+=f*e[1];e=!0}a.a[2]>d.ub&&(a.a[2]=d.ub,e=!0)}a.f[1]<d.wb&&(a.f[1]=d.wb,e=!0);a.f[1]>d.vb&&(a.f[1]=d.vb,e=!0);!0==e&&W(a);if("aboveTerrainOnly"==c.ya)Va(a),a.i.clear(),W(a),Pa(a,a.c.p.A),!0!=
a.pa&&Na(a);else{do a.i.clear(),W(a),Pa(a,a.c.p.A),!0!=a.pa&&Na(a);while(Va(a))}a.O.trim(c.sb/10);a.ca.trim(c.sb);a.Sa=!1}
h.update=function(){if(!0!=this.o){if(null==this.J||"hidden"!=this.J.style.visibility){this.n[0]==this.J.clientWidth&&this.n[1]==this.J.clientHeight||this.rc();null!=this.sc&&this.sc();this.O.update();this.ca.update();if(!0==this.Fc&&(this.fa=this.Lb=this.Mb=0,this.wa=[],this.jb=this.kb=0,this.Qa++,10<=this.Qa)){var a=Date.now();null!=this.Eb&&(this.zb=0.5*(1E3/(a-this.Eb)*this.Qa+this.zb));this.Eb=a}a=performance.now();if(!0==this.w){var b=this.i;b.e.viewport(0,0,b.e.Ub,b.e.Tb);Ka(this)}if(!0==this.Fc&&
(this.ob++,this.lb+=performance.now()-a,100<=this.ob&&(this.xc=this.lb/this.ob,this.ob=this.lb=0),null!=this.Ac&&10<=this.Qa&&(this.Qa=0,!0==this.w))){text_="Redered tiles: "+(this.Mb+this.Lb)+"<br/>Tile cache: "+Math.round(this.ca.size()/1048576)+"MB<br/>Metatile cache: "+Math.round(this.O.size()/1048576)+"MB<br/>GPU cache: "+Math.round(this.Bb.size()/1048576)+"MB<br/>Polygons: "+this.fa+"<br/>Render time: "+Math.round(1E3*this.xc)+"<br/>FPS: "+Math.round(this.zb)+"<br/>Texture files size: "+Math.round(this.jb/
1048576)+"MB<br/>Mesh files size: "+Math.round(this.kb/1048576)+"MB<br/>LODs tiles:<br/>";for(var c in this.wa)text_+="LOD"+c+": "+this.wa[c]+"<br/>";this.Ac.innerHTML=text_}this.w=!1}window.yc(this.update.bind(this))}};h.Kb=function(a){var b=ra(this.h),c=this.h.ea(),d=Sa(this),e=[0,0,0,1],e=s.b.cb(b,[a[0]-d[0]+c[0],a[1]-d[1]+c[1],a[2]-d[2]+c[2],1]);return 0!=e[3]?(a=[0,0,0],a[0]=0.5*(e[0]/e[3]+1)*this.n[0],a[1]=0.5*(-(e[1]/e[3])+1)*this.n[1],a[2]=e[2]/e[3],a):[0,0,0]};
h.Ya=function(a,b){if(null==this.h)return[0,0,1];var c=[2*a/this.n[0]-1,1-2*b/this.n[1],1],d=[c[0],c[1],-1,1],e=s.b.create(),e=s.b.inverse(qa(this.h)),c=[0,0,0,0];s.b.cb(e,d,c);c[2]=-1;c[3]=0;d=s.b.create();d=s.b.inverse(pa(this.h));e=[0,0,0,0];s.b.cb(d,c,e);return e=s.I.normalize([e[0],e[1],e[2]])};
h.Cb=function(a,b){this.Rb=!0;var c=this.i.e;if(!0==this.Rb){var d=this.Ea;P(this.i,this.na);var e=[this.n[0],this.n[1]],f=d,g=d;c.clearColor(1,1,1,1);c.enable(c.DEPTH_TEST);c.viewport(0,0,d,d);c.clear(c.COLOR_BUFFER_BIT|c.DEPTH_BUFFER_BIT);this.n=[f,g];Ka(this,!0);f=e[0];g=e[1];c.clearColor(0,0,0,1);P(this.i,null);d=this.h;d.qb=f/g;d.w=!0;this.n=[f,g];this.i.resize(this.n,!0);this.Rb=!1}if(c.checkFramebufferStatus(c.FRAMEBUFFER)!=c.FRAMEBUFFER_COMPLETE)return[0,0,0,0];g=f=0;f=Math.floor(this.Ea/
this.n[0]*a);g=Math.floor(this.Ea/this.n[1]*b);c=this.na;g=this.Ea-g-1;null!=c.H?(c.i.bindTexture(c),P(c.i,c),d=c.e,e=new Uint8Array(4),d.readPixels(f,g,1,1,d.RGBA,d.UNSIGNED_BYTE,e),P(c.i,null),f=e):f=void 0;c=1/255*f[0]+f[1]+255*f[2]+65025*f[3];f=!(255==f[0]&&255==f[1]&&255==f[2]&&255==f[3]);g=this.Ya(a,b);d=Sa(this);this.$a=[d[0]+g[0]*c,d[1]+g[1]*c,d[2]+g[2]*c];return[this.$a[0],this.$a[1],this.$a[2],f]};function Wa(a,b,c,d){this.c=a;this.B=b;this.K=c;this.G=d;this.Q=this.K.size()+d.naturalWidth*d.naturalHeight*3;this.Gb=c.fileSize();this.Db=d.naturalWidth*d.naturalHeight*3}Wa.prototype.v=function(){null!=this.K&&(this.K.v(),this.K=null);this.G=null};
Wa.prototype.Ba=function(a,b){var c=x(this.c.p,this.B.l),d=c/2+this.B.r-a[0],c=c/2+this.B.s-a[1],e=this.K.j,f=b;null!=f?(f[0]=M(e,0),f[1]=0,f[2]=0,f[3]=0,f[4]=0,f[5]=M(e,1),f[6]=0,f[7]=0,f[8]=0,f[9]=0,f[10]=M(e,2),f[11]=0,f[12]=e.g[0]+d,f[13]=e.g[1]+c,f[14]=e.g[2],f[15]=1):(f=s.b.create(),s.b.multiply(s.sa(e.g[0]+d,e.g[1]+c,e.g[2]),s.mb(M(e,0),M(e,1),M(e,2)),f));return f};Wa.prototype.size=function(){return this.Q};s.Hc=na;
s.Ic=function(a,b,c,d){this.c=a;this.B=b;this.Ja=c;this.Ia=d;this.xb=this.ic=this.lc=!1;this.Ua=function(){!0==this.xb?null!=this.Ia&&this.Ia(this.B):!0==this.lc&&!0==this.ic&&null!=this.Ja&&this.Ja(this.B,new Wa(this.c,this.B,this.K,this.G))}.bind(this);this.G=new Image;this.G.onload=function(){!0!=this.c.o&&(this.ic=!0,this.Ua())}.bind(this);this.G.onerror=function(){!0!=this.c.o&&(this.xb=!0,this.Ua())}.bind(this);this.G.crossOrigin="anonymous";this.G.src=ea(this.c.p,this.B);this.K=new V;this.ed=
function(){!0!=this.c.o&&(this.lc=!0,this.Ua())}.bind(this);this.dd=function(){!0!=this.c.o&&(this.xb=!0,this.Ua())}.bind(this);this.K.load(da(this.c.p,this.B),this.ed,this.dd)};function u(a,b,c,d){this.c=a;this.l=null!=b?b:0;this.r=null!=c?c:0;this.s=null!=d?d:0}function N(a,b){var c=x(a.c.p,a.l),d=a.r+c/2,c=a.s+c/2;switch(b){case 0:return new u(a.c,a.l+1,a.r,a.s);case 1:return new u(a.c,a.l+1,d,a.s);case 2:return new u(a.c,a.l+1,a.r,c);case 3:return new u(a.c,a.l+1,d,c)}}u.prototype.parent=function(){var a=x(this.c.p,this.l),b=this.c.p.A;return new u(this.c,this.l-1,b.r+((this.r-b.r)/a&-2)*a,b.s+((this.s-b.s)/a&-2)*a)};
u.prototype.isEqual=function(a){return this.l==a.l&&this.r==a.r&&this.s==a.s};function $(a,b,c,d,e){if(null!=b&&""!=b){this.N=[];this.D=[];this.U=[];this.Qb=this.m=this.p=this.d=null;this.o=!1;this.J=null;var f="";"string"===typeof b&&(f=b.split("?")[0].split("/").slice(0,-1).join("/")+"/");"string"===typeof a?this.J=document.getElementById(a):"object"===typeof a&&(this.J=a);if(null==this.J)null!=d&&d(!1,"DOM element does not exist");else{var g=null,k=null,l=function(){null==g||null==k&&null!=c||(this.p=new aa(this,g,f),this.m=new ha(k),this.Qb=e,this.d=new Ea(this,this.J,
this.fd.bind(this)),null!=d&&d(!0))}.bind(this);a=function(a){g=a;l()}.bind(this);var m=function(a){k=a;l()}.bind(this),n=function(a){null!=d&&d(!1,a+" config not found")}.bind(this);null!=c&&"string"===typeof c&&s.kc(c,m,n.bind(this,"browser"));"string"===typeof b&&s.kc(b,a,n.bind(this,"map"));"object"===typeof b&&(g=b);"object"===typeof c&&(k=c);null==g&&null==k||l()}}}h=$.prototype;h.v=function(){this.d.v();this.o=!0};
h.rd=function(a){if(!0!=this.o&&null!=this.d&&null!=this.d.h&&this.m.R!=a){if("manual"==a){var b=s.Hd(this.d.a[0],this.d.a[1]);b[0]>this.d.a[2]&&(this.d.a[2]=b[0]+100)}this.m.R=a;W(this.d);this.N=[];this.U=[];this.D=[]}};h.Rc=function(){return this.m.R};h.Na=function(a,b,c){!0!=this.o&&null!=this.d&&(this.d.a=[a,b,c],W(this.d))};h.ea=function(){return!0==this.o||null==this.d?[0,0,0]:[this.d.a[0],this.d.a[1],this.d.a[2]]};h.Ma=function(a,b,c){!0!=this.o&&null!=this.d&&(this.d.f=[a,b,c],W(this.d))};
h.Ab=function(){return!0==this.o||null==this.d?[0,0,0]:this.d.f};h.pd=function(a,b){if(null!=this.d&&null!=this.d.h){var c=this.d.h;c.ac=a;c.Hb=20;c.Aa=b;c.w=!0;W(this.d)}};h.qd=function(a){!0!=this.o&&null!=this.d&&null!=this.d.h&&(this.m.ya=a,W(this.d))};h.Qc=function(){return this.m.ya};h.Cb=function(a,b){return null==this.d?[0,0,0,!1]:this.d.Cb(a,b,"all")};h.Kb=function(a,b,c){return null==this.d?[0,0,0]:this.d.Kb(a,b,c)};h.Cd=function(){return[[0,0],[1,0],[0,1]]};
h.Ya=function(a,b){if(null==this.d)return[0,0,0,!1];var c=this.Ya(a,b);return[Sa(this),c]};h.Sc=function(a,b){if(!0!=this.o&&null!=this.d)return s.Ra(this.c,[a,b],this.d.O)};h.gd=function(a,b){if(!0!=this.o&&null!=this.d){var c=Z(this.d)/800;a*=c;b*=c;var d=s.X(this.Ab()[0]),c=[-Math.sin(d),Math.cos(d)],d=[Math.cos(d),Math.sin(d)];this.d.a[0]+=c[0]*b-d[0]*a;this.d.a[1]+=c[1]*b-d[1]*a;0<this.m.ka[0]&&this.N.push([c[0]*b-d[0]*a,c[1]*b-d[1]*a]);W(this.d)}};
h.rotate=function(a,b,c){!0!=this.o&&null!=this.d&&(null==c&&(c=0),this.d.f[0]+=0.3*-a,this.d.f[1]+=0.3*-b,this.d.f[2]+=0.3*c,0<this.m.ka[1]&&this.D.push([0.3*-a,0.3*-b,0.3*c]),this.d.Sa=!0,W(this.d))};h.zoom=function(a){!0!=this.o&&null!=this.d&&(a=1+0.001*a,this.d.a[2]*=a,0<this.m.ka[2]&&this.U.push([a]),W(this.d))};
h.fd=function(){if(!0!=this.o&&null!=this.d){var a=!1,b=this.m.ka[0],c=this.m.ka[1],d=this.m.ka[2];0<this.D.length&&0==this.N.length&&0==this.U.length&&(this.d.Sa=!0);for(var e=0;e<this.N.length;e++)this.N[e][0]*=b,this.N[e][1]*=b,this.d.a[0]+=this.N[e][0],this.d.a[1]+=this.N[e][1],0.01>Math.abs(this.N[e][0])+Math.abs(this.N[e][1])&&(this.N.splice(e,1),e--),a=!0;for(e=0;e<this.U.length;e++)this.U[e][0]+=(1-this.U[e][0])*(1-d),this.d.a[2]*=this.U[e][0],this.d.a[2]=Math.min(this.d.a[2],4E5),0.001>Math.abs(1-
this.U[e][0])&&(this.U.splice(e,1),e--),a=!0;for(e=0;e<this.D.length;e++)this.D[e][0]*=c,this.D[e][1]*=c,this.D[e][2]*=c,this.d.f[0]+=this.D[e][0],this.d.f[1]+=this.D[e][1],this.d.f[2]+=this.D[e][2],0.01>Math.abs(this.D[e][0])+Math.abs(this.D[e][1])+Math.abs(this.D[e][2])&&(this.D.splice(e,1),e--),a=!0;!0==a&&W(this.d);null!=this.Qb&&this.Qb()}};
s.Kc=function(){var a=document.createElement("canvas");if(null==a)return!1;a.width=1024;a.height=768;if(null==a.getContext)return!1;var b=null;try{b=a.getContext("webgl")||a.getContext("experimental-webgl")}catch(c){return!1}return b?!0:!1};s.Browser=$;$.prototype.setControlMode=$.prototype.rd;$.prototype.getControlMode=$.prototype.Rc;$.prototype.setPosition=$.prototype.Na;$.prototype.getPosition=$.prototype.ea;$.prototype.setOrientation=$.prototype.Ma;$.prototype.getOrientation=$.prototype.Ab;
$.prototype.setCamera=$.prototype.pd;$.prototype.setCameraConstrainMode=$.prototype.qd;$.prototype.getCameraConstrainMode=$.prototype.Qc;$.prototype.hitTest=$.prototype.Cb;$.prototype.project=$.prototype.Kb;$.prototype.getScreenRay=$.prototype.Ya;$.prototype.getTerrainHeight=$.prototype.Sc;$.prototype.visibleArea=$.prototype.Cd;$.prototype.pan=$.prototype.gd;$.prototype.rotate=$.prototype.rotate;$.prototype.zoom=$.prototype.zoom;$.prototype.kill=$.prototype.v;s.checkSupport=s.Kc;
