var h,s={};window.Vadstena=s;window.ga=null!=window.ga?window.ga:{};window.VadstenaMap_=null!=window.VadstenaMap_?window.VadstenaMap_:null;s.Ia=Array;s.ze={};s.ze.create=function(a){var b=new s.Ia(2);a&&(b[0]=a[0],b[1]=a[1]);return b};s.rc={};s.rc.create=function(a){var b=new s.Ia(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b};s.rc.zc=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]};s.N={};s.N.create=function(a){var b=new s.Ia(3);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2]);return b};s.N.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b};
s.N.add=function(a,b,c){if(!c||a==c)return a[0]+=b[0],a[1]+=b[1],a[2]+=b[2],a;c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c};s.N.Re=function(a,b,c){if(!c||a==c)return a[0]-=b[0],a[1]-=b[1],a[2]-=b[2],a;c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c};s.N.Ke=function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b};s.N.scale=function(a,b,c){if(!c||a==c)return a[0]*=b,a[1]*=b,a[2]*=b,a;c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c};
s.N.normalize=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=Math.sqrt(c*c+d*d+e*e);if(g){if(1==g)return b[0]=c,b[1]=d,b[2]=e,b}else return b[0]=0,b[1]=0,b[2]=0,b;g=1/g;b[0]=c*g;b[1]=d*g;b[2]=e*g;return b};s.N.De=function(a,b,c){c||(c=a);var d=a[0],e=a[1];a=a[2];var g=b[0],f=b[1];b=b[2];c[0]=e*b-a*f;c[1]=a*g-d*b;c[2]=d*f-e*g;return c};s.N.length=function(a){var b=a[0],c=a[1];a=a[2];return Math.sqrt(b*b+c*c+a*a)};s.N.zc=function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]};
s.N.direction=function(a,b,c){c||(c=a);var d=a[0]-b[0],e=a[1]-b[1];a=a[2]-b[2];b=Math.sqrt(d*d+e*e+a*a);if(!b)return c[0]=0,c[1]=0,c[2]=0,c;b=1/b;c[0]=d*b;c[1]=e*b;c[2]=a*b;return c};s.N.Ge=function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);return d};s.N.nc=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+"]"};s.ja={};
s.ja.create=function(a){var b=new s.Ia(9);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9]);return b};s.ja.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b};s.ja.Kc=function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a};
s.ja.Ma=function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[5];a[1]=a[3];a[2]=a[6];a[3]=c;a[5]=a[7];a[6]=d;a[7]=e;return a}b[0]=a[0];b[1]=a[3];b[2]=a[6];b[3]=a[1];b[4]=a[4];b[5]=a[7];b[6]=a[2];b[7]=a[5];b[8]=a[8];return b};s.ja.ye=function(a,b){b||(b=s.c.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=0;b[4]=a[3];b[5]=a[4];b[6]=a[5];b[7]=0;b[8]=a[6];b[9]=a[7];b[10]=a[8];b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};
s.ja.nc=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+"]"};s.c={};s.c.create=function(a){var b=new s.Ia(16);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9],b[10]=a[10],b[11]=a[11],b[12]=a[12],b[13]=a[13],b[14]=a[14],b[15]=a[15]);return b};
s.c.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b};s.c.Kc=function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a};
s.c.Ma=function(a,b){if(!b||a==b){var c=a[1],d=a[2],e=a[3],g=a[6],f=a[7],k=a[11];a[1]=a[4];a[2]=a[8];a[3]=a[12];a[4]=c;a[6]=a[9];a[7]=a[13];a[8]=d;a[9]=g;a[11]=a[14];a[12]=e;a[13]=f;a[14]=k;return a}b[0]=a[0];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=a[1];b[5]=a[5];b[6]=a[9];b[7]=a[13];b[8]=a[2];b[9]=a[6];b[10]=a[10];b[11]=a[14];b[12]=a[3];b[13]=a[7];b[14]=a[11];b[15]=a[15];return b};
s.c.Ee=function(a){var b=a[0],c=a[1],d=a[2],e=a[3],g=a[4],f=a[5],k=a[6],l=a[7],m=a[8],n=a[9],p=a[10],q=a[11],r=a[12],t=a[13],v=a[14];a=a[15];return r*n*k*e-m*t*k*e-r*f*p*e+g*t*p*e+m*f*v*e-g*n*v*e-r*n*d*l+m*t*d*l+r*c*p*l-b*t*p*l-m*c*v*l+b*n*v*l+r*f*d*q-g*t*d*q-r*c*k*q+b*t*k*q+g*c*v*q-b*f*v*q-m*f*d*a+g*n*d*a+m*c*k*a-b*n*k*a-g*c*p*a+b*f*p*a};
s.c.inverse=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=a[3],f=a[4],k=a[5],l=a[6],m=a[7],n=a[8],p=a[9],q=a[10],r=a[11],t=a[12],v=a[13],z=a[14],A=a[15],I=c*k-d*f,J=c*l-e*f,B=c*m-g*f,C=d*l-e*k,D=d*m-g*k,E=e*m-g*l,F=n*v-p*t,G=n*z-q*t,H=n*A-r*t,N=p*z-q*v,O=p*A-r*v,P=q*A-r*z,x=1/(I*P-J*O+B*N+C*H-D*G+E*F);b[0]=(k*P-l*O+m*N)*x;b[1]=(-d*P+e*O-g*N)*x;b[2]=(v*E-z*D+A*C)*x;b[3]=(-p*E+q*D-r*C)*x;b[4]=(-f*P+l*H-m*G)*x;b[5]=(c*P-e*H+g*G)*x;b[6]=(-t*E+z*B-A*J)*x;b[7]=(n*E-q*B+r*J)*x;b[8]=(f*O-k*H+m*F)*x;b[9]=
(-c*O+d*H-g*F)*x;b[10]=(t*D-v*B+A*I)*x;b[11]=(-n*D+p*B-r*I)*x;b[12]=(-f*N+k*G-l*F)*x;b[13]=(c*N-d*G+e*F)*x;b[14]=(-t*C+v*J-z*I)*x;b[15]=(n*C-p*J+q*I)*x;return b};s.c.We=function(a,b){b||(b=s.c.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};
s.c.xe=function(a,b){b||(b=s.ja.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b};s.c.Ve=function(a,b){var c=a[0],d=a[1],e=a[2],g=a[4],f=a[5],k=a[6],l=a[8],m=a[9],n=a[10],p=n*f-k*m,q=-n*g+k*l,r=m*g-f*l,t=c*p+d*q+e*r;if(!t)return null;t=1/t;b||(b=s.ja.create());b[0]=p*t;b[1]=(-n*d+e*m)*t;b[2]=(k*d-e*f)*t;b[3]=q*t;b[4]=(n*c-e*l)*t;b[5]=(-k*c+e*g)*t;b[6]=r*t;b[7]=(-m*c+d*l)*t;b[8]=(f*c-d*g)*t;return b};
s.c.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],g=a[2],f=a[3],k=a[4],l=a[5],m=a[6],n=a[7],p=a[8],q=a[9],r=a[10],t=a[11],v=a[12],z=a[13],A=a[14];a=a[15];var I=b[0],J=b[1],B=b[2],C=b[3],D=b[4],E=b[5],F=b[6],G=b[7],H=b[8],N=b[9],O=b[10],P=b[11],x=b[12],ba=b[13],ca=b[14];b=b[15];c[0]=I*d+J*k+B*p+C*v;c[1]=I*e+J*l+B*q+C*z;c[2]=I*g+J*m+B*r+C*A;c[3]=I*f+J*n+B*t+C*a;c[4]=D*d+E*k+F*p+G*v;c[5]=D*e+E*l+F*q+G*z;c[6]=D*g+E*m+F*r+G*A;c[7]=D*f+E*n+F*t+G*a;c[8]=H*d+N*k+O*p+P*v;c[9]=H*e+N*l+O*q+P*z;c[10]=H*
g+N*m+O*r+P*A;c[11]=H*f+N*n+O*t+P*a;c[12]=x*d+ba*k+ca*p+b*v;c[13]=x*e+ba*l+ca*q+b*z;c[14]=x*g+ba*m+ca*r+b*A;c[15]=x*f+ba*n+ca*t+b*a;return c};s.c.Aa=function(a,b,c){c||(c=b);var d=b[0],e=b[1];b=b[2];c[0]=a[0]*d+a[4]*e+a[8]*b+a[12];c[1]=a[1]*d+a[5]*e+a[9]*b+a[13];c[2]=a[2]*d+a[6]*e+a[10]*b+a[14];return c};
s.c.xb=function(a,b,c){c||(c=b);var d=b[0],e=b[1],g=b[2];b=b[3];c[0]=a[0]*d+a[4]*e+a[8]*g+a[12]*b;c[1]=a[1]*d+a[5]*e+a[9]*g+a[13]*b;c[2]=a[2]*d+a[6]*e+a[10]*g+a[14]*b;c[3]=a[3]*d+a[7]*e+a[11]*g+a[15]*b;return c};
s.c.translate=function(a,b,c){var d=b[0],e=b[1];b=b[2];if(!c||a==c)return a[12]=a[0]*d+a[4]*e+a[8]*b+a[12],a[13]=a[1]*d+a[5]*e+a[9]*b+a[13],a[14]=a[2]*d+a[6]*e+a[10]*b+a[14],a[15]=a[3]*d+a[7]*e+a[11]*b+a[15],a;var g=a[0],f=a[1],k=a[2],l=a[3],m=a[4],n=a[5],p=a[6],q=a[7],r=a[8],t=a[9],v=a[10],z=a[11];c[0]=g;c[1]=f;c[2]=k;c[3]=l;c[4]=m;c[5]=n;c[6]=p;c[7]=q;c[8]=r;c[9]=t;c[10]=v;c[11]=z;c[12]=g*d+m*e+r*b+a[12];c[13]=f*d+n*e+t*b+a[13];c[14]=k*d+p*e+v*b+a[14];c[15]=l*d+q*e+z*b+a[15];return c};
s.c.scale=function(a,b,c){var d=b[0],e=b[1];b=b[2];if(!c||a==c)return a[0]*=d,a[1]*=d,a[2]*=d,a[3]*=d,a[4]*=e,a[5]*=e,a[6]*=e,a[7]*=e,a[8]*=b,a[9]*=b,a[10]*=b,a[11]*=b,a;c[0]=a[0]*d;c[1]=a[1]*d;c[2]=a[2]*d;c[3]=a[3]*d;c[4]=a[4]*e;c[5]=a[5]*e;c[6]=a[6]*e;c[7]=a[7]*e;c[8]=a[8]*b;c[9]=a[9]*b;c[10]=a[10]*b;c[11]=a[11]*b;c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15];return c};
s.c.rotate=function(a,b,c,d){var e=c[0],g=c[1];c=c[2];var f=Math.sqrt(e*e+g*g+c*c);if(!f)return null;1!=f&&(f=1/f,e*=f,g*=f,c*=f);var k=Math.sin(b),l=Math.cos(b),m=1-l;b=a[0];var f=a[1],n=a[2],p=a[3],q=a[4],r=a[5],t=a[6],v=a[7],z=a[8],A=a[9],I=a[10],J=a[11],B=e*e*m+l,C=g*e*m+c*k,D=c*e*m-g*k,E=e*g*m-c*k,F=g*g*m+l,G=c*g*m+e*k,H=e*c*m+g*k,e=g*c*m-e*k,g=c*c*m+l;d?a!=d&&(d[12]=a[12],d[13]=a[13],d[14]=a[14],d[15]=a[15]):d=a;d[0]=b*B+q*C+z*D;d[1]=f*B+r*C+A*D;d[2]=n*B+t*C+I*D;d[3]=p*B+v*C+J*D;d[4]=b*E+q*
F+z*G;d[5]=f*E+r*F+A*G;d[6]=n*E+t*F+I*G;d[7]=p*E+v*F+J*G;d[8]=b*H+q*e+z*g;d[9]=f*H+r*e+A*g;d[10]=n*H+t*e+I*g;d[11]=p*H+v*e+J*g;return d};s.c.Ne=function(a,b,c){var d=Math.sin(b);b=Math.cos(b);var e=a[4],g=a[5],f=a[6],k=a[7],l=a[8],m=a[9],n=a[10],p=a[11];c?a!=c&&(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[4]=e*b+l*d;c[5]=g*b+m*d;c[6]=f*b+n*d;c[7]=k*b+p*d;c[8]=e*-d+l*b;c[9]=g*-d+m*b;c[10]=f*-d+n*b;c[11]=k*-d+p*b;return c};
s.c.Oe=function(a,b,c){var d=Math.sin(b);b=Math.cos(b);var e=a[0],g=a[1],f=a[2],k=a[3],l=a[8],m=a[9],n=a[10],p=a[11];c?a!=c&&(c[4]=a[4],c[5]=a[5],c[6]=a[6],c[7]=a[7],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+l*-d;c[1]=g*b+m*-d;c[2]=f*b+n*-d;c[3]=k*b+p*-d;c[8]=e*d+l*b;c[9]=g*d+m*b;c[10]=f*d+n*b;c[11]=k*d+p*b;return c};
s.c.Pe=function(a,b,c){var d=Math.sin(b);b=Math.cos(b);var e=a[0],g=a[1],f=a[2],k=a[3],l=a[4],m=a[5],n=a[6],p=a[7];c?a!=c&&(c[8]=a[8],c[9]=a[9],c[10]=a[10],c[11]=a[11],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=e*b+l*d;c[1]=g*b+m*d;c[2]=f*b+n*d;c[3]=k*b+p*d;c[4]=e*-d+l*b;c[5]=g*-d+m*b;c[6]=f*-d+n*b;c[7]=k*-d+p*b;return c};
s.c.Bd=function(a,b,c,d,e,g,f){f||(f=s.c.create());var k=b-a,l=d-c,m=g-e;f[0]=2*e/k;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=2*e/l;f[6]=0;f[7]=0;f[8]=(b+a)/k;f[9]=(d+c)/l;f[10]=-(g+e)/m;f[11]=-1;f[12]=0;f[13]=0;f[14]=-(g*e*2)/m;f[15]=0;return f};s.c.perspective=function(a,b,c,d,e){a=c*Math.tan(a*Math.PI/360);b*=a;return s.c.Bd(-b,b,-a,a,c,d,e)};
s.c.Me=function(a,b,c,d,e,g,f){f||(f=s.c.create());var k=b-a,l=d-c,m=g-e;f[0]=2/k;f[1]=0;f[2]=0;f[3]=0;f[4]=0;f[5]=2/l;f[6]=0;f[7]=0;f[8]=0;f[9]=0;f[10]=-2/m;f[11]=0;f[12]=-(a+b)/k;f[13]=-(d+c)/l;f[14]=-(g+e)/m;f[15]=1;return f};
s.c.He=function(a,b,c,d){d||(d=s.c.create());var e=a[0],g=a[1];a=a[2];var f=c[0],k=c[1],l=c[2];c=b[1];var m=b[2];if(e==b[0]&&g==c&&a==m)return s.c.Kc(d);var n,p,q,r;c=e-b[0];m=g-b[1];b=a-b[2];r=1/Math.sqrt(c*c+m*m+b*b);c*=r;m*=r;b*=r;n=k*b-l*m;l=l*c-f*b;f=f*m-k*c;(r=Math.sqrt(n*n+l*l+f*f))?(r=1/r,n*=r,l*=r,f*=r):f=l=n=0;k=m*f-b*l;p=b*n-c*f;q=c*l-m*n;(r=Math.sqrt(k*k+p*p+q*q))?(r=1/r,k*=r,p*=r,q*=r):q=p=k=0;d[0]=n;d[1]=k;d[2]=c;d[3]=0;d[4]=l;d[5]=p;d[6]=m;d[7]=0;d[8]=f;d[9]=q;d[10]=b;d[11]=0;d[12]=
-(n*e+l*g+f*a);d[13]=-(k*e+p*g+q*a);d[14]=-(c*e+m*g+b*a);d[15]=1;return d};s.c.nc=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+"]"};s.X={};s.X.create=function(a){var b=new s.Ia(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b};s.X.set=function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b};
s.X.Ce=function(a,b){var c=a[0],d=a[1],e=a[2];if(!b||a==b)return a[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e)),a;b[0]=c;b[1]=d;b[2]=e;b[3]=-Math.sqrt(Math.abs(1-c*c-d*d-e*e));return b};s.X.inverse=function(a,b){if(!b||a==b)return a[0]*=1,a[1]*=1,a[2]*=1,a;b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b};s.X.length=function(a){var b=a[0],c=a[1],d=a[2];a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)};
s.X.normalize=function(a,b){b||(b=a);var c=a[0],d=a[1],e=a[2],g=a[3],f=Math.sqrt(c*c+d*d+e*e+g*g);if(0==f)return b[0]=0,b[1]=0,b[2]=0,b[3]=0,b;f=1/f;b[0]=c*f;b[1]=d*f;b[2]=e*f;b[3]=g*f;return b};s.X.multiply=function(a,b,c){c||(c=a);var d=a[0],e=a[1],g=a[2];a=a[3];var f=b[0],k=b[1],l=b[2];b=b[3];c[0]=d*b+a*f+e*l-g*k;c[1]=e*b+a*k+g*f-d*l;c[2]=g*b+a*l+d*k-e*f;c[3]=a*b-d*f-e*k-g*l;return c};
s.X.Aa=function(a,b,c){c||(c=b);var d=b[0],e=b[1],g=b[2];b=a[0];var f=a[1],k=a[2];a=a[3];var l=a*d+f*g-k*e,m=a*e+k*d-b*g,n=a*g+b*e-f*d,d=-b*d-f*e-k*g;c[0]=l*a+d*-b+m*-k-n*-f;c[1]=m*a+d*-f+n*-b-l*-k;c[2]=n*a+d*-k+l*-f-m*-b;return c};s.X.xe=function(a,b){b||(b=s.ja.create());var c=a[0],d=a[1],e=a[2],g=a[3],f=c+c,k=d+d,l=e+e,m=c*f,n=c*k,c=c*l,p=d*k,d=d*l,e=e*l,f=g*f,k=g*k,g=g*l;b[0]=1-(p+e);b[1]=n-g;b[2]=c+k;b[3]=n+g;b[4]=1-(m+e);b[5]=d-f;b[6]=c-k;b[7]=d+f;b[8]=1-(m+p);return b};
s.X.ye=function(a,b){b||(b=s.c.create());var c=a[0],d=a[1],e=a[2],g=a[3],f=c+c,k=d+d,l=e+e,m=c*f,n=c*k,c=c*l,p=d*k,d=d*l,e=e*l,f=g*f,k=g*k,g=g*l;b[0]=1-(p+e);b[1]=n-g;b[2]=c+k;b[3]=0;b[4]=n+g;b[5]=1-(m+e);b[6]=d-f;b[7]=0;b[8]=c-k;b[9]=d+f;b[10]=1-(m+p);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b};s.X.Qe=function(a,b,c,d){d||(d=a);var e=c;0>a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]&&(e=-1*c);d[0]=1-c*a[0]+e*b[0];d[1]=1-c*a[1]+e*b[1];d[2]=1-c*a[2]+e*b[2];d[3]=1-c*a[3]+e*b[3];return d};
s.X.nc=function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"};s.Cd=function(a,b,c,d,e,g){var f=b-a,k=d-c,l=g-e;a=s.c.create([2*e/f,0,(b+a)/f,0,0,2*e/k,(d+c)/k,0,0,0,-(g+e)/l,-2*g*e/l,0,0,-1,0]);s.c.Ma(a);return a};s.Zd=function(a,b,c,d){a=c*Math.tan(a*Math.PI/360);b*=a;return s.Cd(-b,b,-a,a,c,d)};s.na=function(a,b){var c=Math.cos(b),d=Math.sin(b);switch(a){case 0:c=s.c.create([1,0,0,0,0,c,-d,0,0,d,c,0,0,0,0,1]);break;case 1:c=s.c.create([c,0,-d,0,0,1,0,0,d,0,c,0,0,0,0,1]);break;default:c=s.c.create([c,-d,0,0,d,c,0,0,0,0,1,0,0,0,0,1])}s.c.Ma(c);return c};
s.Eb=function(a,b,c){a=s.c.create([a,0,0,0,0,b,0,0,0,0,c,0,0,0,0,1]);s.c.Ma(a);return a};s.fe=function(a){return s.Eb(a,a,a)};s.Fa=function(a,b,c){a=s.c.create([1,0,0,a,0,1,0,b,0,0,1,c,0,0,0,1]);s.c.Ma(a);return a};s.Xe=function(a){return s.Fa(a[0],a[1],0)};s.Ye=function(a){return s.Fa(a[0],a[1],a[2])};s.fa=function(a,b,c){a<b?a=b:a>c&&(a=c);return a};s.P=function(a){return a*Math.PI/180};s.Xc=function(a){var b=7;if(0>a)return a=-a+"",b--,a.length>=b?"-"+a:"-"+(Array(b-a.length+1).join("0")+a);a+="";return a.length>=b?a:Array(b-a.length+1).join("0")+a};s.yc=function(a){var b=(a&31744)>>10;fraction=a&1023;return(a>>15?-1:1)*(b?31===b?fraction?NaN:Infinity:Math.pow(2,b-15)*(1+fraction/1024):fraction/1024*6.103515625E-5)};
s.ke=function(a,b){return a.replace(/\{([_$a-zA-Z0-9][_$a-zA-Z0-9]*)\}/g,function(a,d){return d in b?b[d]:a})};s.gc=function(a,b,c){var d=new XMLHttpRequest;d.onload=function(){var a=d.response;try{var g=eval("("+a+")")}catch(f){null!=c&&c();return}null!=b&&b(g)}.bind(this);d.onerror=function(){null!=c&&c()}.bind(this);d.open("GET",a,!0);d.send("")};
s.Mc=function(a,b,c){var d=new XMLHttpRequest;d.onreadystatechange=function(){switch(d.readyState){case 0:case 1:case 2:case 3:break;case 4:if(404==d.status){null!=c&&c();break}var a=new DataView(d.response);null!=b&&b(a);break;default:null!=c&&c()}}.bind(this);d.onerror=function(){null!=c&&c()}.bind(this);d.open("GET",a,!0);d.responseType="arraybuffer";d.send("")};window.performance=window.performance||{};
performance.now=performance.now||performance.Ie||performance.Je||performance.Le||performance.webkitNow||function(){return(new Date).getTime()};window.dd=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)};function aa(a,b,c){this.json=b;this.v=new u(a);this.Qc=this.Rc=this.Yb=0;this.mb=[];this.lb=[0,0,0];this.ud=c;this.nd=this.Pc=this.Sc="";null!=b.foat&&(this.v.k=b.foat[0],this.v.q=b.foat[1],this.v.r=b.foat[2],this.Yb=b.foat[3]);null!=b.meta&&(this.Rc=b.meta[0],this.Qc=b.meta[1]);this.Sc=b.metaTemplate;this.Pc=b.meshTemplate;this.nd=b.textureTemplate;if(null!=b.defaultPosition&&null!=b.defaultOrientation)for(a=0;3>a;a++)this.mb[a]=b.defaultPosition[a],this.lb[a]=b.defaultOrientation[a];this.ne=null!=
b.texelSize?b.texelSize:0.02;Math.log(w(this,0));Math.log(2);Math.log(32);Math.log(2);this.Pd=null}function w(a,b){return b>a.v.k?a.Yb>>b-a.v.k:a.Yb<<a.v.k-b}function da(a,b){return ea(a,a.Sc,b)}function fa(a,b){return ea(a,a.Pc,b)}function ha(a,b){return ea(a,a.nd,b)}function ea(a,b,c){b=s.ke(b,{lod:c.k,easting:s.Xc(c.q),northing:s.Xc(c.r)});return a.ud+b}
function ia(a,b,c){var d=w(a,11),e=Math.round((b[0]-a.v.q)/d),g=Math.round((b[1]-a.v.r)/d);return null!=c?(c[0]=a.v.q+e*d,c[1]=a.v.r+g*d,c[2]=b[2],c):[a.v.q+e*d,a.v.r+g*d,b[2]]}
function ja(a){this.Kb=1073741824;this.Fc=402653184;this.Wa=4;this.vc=45;this.ib=6E5;this.K=180;this.Lb=this.ib;this.Nb=-90;this.Mb=-10;this.pa="aboveTerrainOnly";this.ea=0.5*this.K;this.Gc=8;this.Hc=32;this.Jc=1024;this.Ea="./skydome.jpg";this.wa=[0.8,0.8,0.8];this.Z="observer";if(null!=a&&(null!=a.cacheSize&&(this.Kb=a.cacheSize),null!=a.gpuCacheSize&&(this.Fc=a.gpuCacheSize),null!=a.numThreads&&(this.Wa=a.numThreads),null!=a.cameraFOV&&(this.vc=a.cameraFOV),null!=a.cameraVisibility&&(this.ib=a.cameraVisibility),
null!=a.cameraMinDistance&&(this.K=a.cameraMinDistance),null!=a.cameraMaxDistance&&(this.Lb=a.cameraMaxDistance),null!=a.cameraMinTilt&&(this.Nb=a.cameraMinTilt),null!=a.cameraMaxTilt&&(this.Mb=a.cameraMaxTilt),null!=a.cameraConstrainMode&&(this.pa=a.cameraConstrainMode,this.ea=this.K/5),null!=a.gridEmbeddingFactor&&(this.Gc=a.gridEmbeddingFactor),null!=a.gridMinTileSize&&(this.Hc=a.gridMinTileSize),null!=a.skydomeTexture&&(this.Ea=a.skydomeTexture),null!=a.hitTextureSize&&(this.Jc=a.hitTextureSize),
null!=a.controlMode&&(this.Z=a.controlMode),null!=a.controlInertia))for(var b=0;3>b;b++)this.wa[b]=a.controlInertia[b]};function ka(a,b,c,d,e,g){this.h=[];this.m=[];this.h[0]=null!=a?a:Number.POSITIVE_INFINITY;this.h[1]=null!=b?b:Number.POSITIVE_INFINITY;this.h[2]=null!=c?c:Number.POSITIVE_INFINITY;this.m[0]=null!=d?d:Number.NEGATIVE_INFINITY;this.m[1]=null!=e?e:Number.NEGATIVE_INFINITY;this.m[2]=null!=g?g:Number.NEGATIVE_INFINITY}function y(a,b){return a.m[b]-a.h[b]}function la(a,b){return new ka(a.h[0]-b[0],a.h[1]-b[1],a.h[2],a.m[0]-b[0],a.m[1]-b[1],a.m[2])};function ma(a){this.za=[];this.wb=null!=a?a:Number.MAX_VALUE;this.S=this.da=null;this.sa=0}h=ma.prototype;h.log=function(){for(var a=0,b=this.S;null!=b.la&&!(b=this.za[b.la][3],a++,10<a););this.za.forEach(function(){})};h.find=function(a){a=this.hash(a);a=this.za[a];if(null!=a){if(this.S!=a){null!=a.ma&&(a.ma.la=a.la);null!=a.la&&(a.la.ma=a.ma);this.da==a&&(this.da=a.ma);var b=this.S;this.S=a;this.S.la=b;this.S.ma=null;b.ma=this.S}return a.tb}return null};h.contains=function(a){return null!=this.za[this.hash(a)]};
h.clear=function(){for(var a=this.S;null!=a;)null!=a.tb&&a.tb.w(),a=a.la;this.za=[];this.S=this.da=null;this.sa=0};function na(a,b,c,d){b=a.hash(b);c={Id:b,tb:c,zd:d,ma:null,la:a.S};null!=a.S&&(a.S.ma=c);a.S=c;null==a.da&&(a.da=c);a.za[b]=c;a.sa+=d;oa(a)}function oa(a){for(;a.sa>a.wb;){var b=a.da;if(null!=b)a.da=a.da.ma,null!=a.da&&(a.da.la=null),a.za[b.Id]=null,a.sa-=b.zd,b.tb.w();else break}}h.hash=function(a){return""+Math.round(a.k)+"."+Math.round(a.q)+"."+Math.round(a.r)};
function pa(a,b,c,d,e){null==d&&(d=1);this.d=a;this.Wa=d;this.Ib=0;this.J=new ma(b);this.Ca=[];this.Ab=[];this.xa=[];this.Uc=c;this.Ac=e}h=pa.prototype;h.get=function(a){var b=this.J.find(a);null==b&&this.ic(a);return b};h.contains=function(a){return this.J.contains(a)};h.trim=function(a){var b=this.J.wb,c=this.J;c.wb=a;oa(c);a=this.J;a.wb=b;oa(a)};h.reset=function(){this.J.clear()};h.size=function(){return this.J.sa};
h.ic=function(a){var b=this.J.hash(a),c=this.xa.indexOf(b);-1==c&&(c=this.Ca.indexOf(b),-1!=c&&(this.Ca.splice(c,1),this.Ab.splice(c,1)),this.Ca.unshift(b),this.Ab.unshift(a),20<this.Ca.length&&(this.Ca.pop(),this.Ab.pop()))};
h.update=function(){if(0<this.Ca.length&&this.Ib<this.Wa){var a=this.Ca.shift(),b=this.Ab.shift();if(-1==this.xa.indexOf(a)){this.xa.push(a);this.Ib++;var a=function(a,b){this.xa.splice(this.xa.indexOf(this.J.hash(a)),1);this.Ib--;na(this.J,a,b,b.size());null!=this.Uc&&this.Uc(a)}.bind(this),c=function(a){this.xa.splice(this.xa.indexOf(this.J.hash(a)),1);this.Ib--}.bind(this);null!=this.Ac&&new this.Ac(this.d,b,a,c)}}};function qa(a,b,c,d){this.Yd=a;this.a=[0,0,0];this.g=[0,0,0];this.Na=1;this.Dc=b;this.Va=c;this.Ha=d;this.ka=s.c.create();this.$a=s.c.create();this.yb=s.c.create();this.ha=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]];this.ed=[0,0,0,0];this.B=!0}h=qa.prototype;h.La=function(a){this.a=a;this.B=!0};h.Ka=function(a){this.g=a;this.B=!0};h.ia=function(){return[this.a[0],this.a[1],this.a[2]]};h.ob=function(){return[this.g[0],this.g[1],this.g[2]]};
function ra(a){a.B&&a.update();return a.ka}function K(a){a.B&&a.update();return a.$a}function sa(a){a.B&&a.update();return a.yb}function L(a,b,c){a.B&&a.update();s.c.Aa(a.ka,b,a.ed);b=s.N.length(a.ed);return!0==c?b<a.Va?[Number.POSITIVE_INFINITY,b]:[a.$a[0]/b,b]:b<a.Va?Number.POSITIVE_INFINITY:a.$a[0]/b}
function ta(a,b){a.B&&a.update();for(var c=[[b.h[0],b.h[1],b.h[2],1],[b.h[0],b.h[1],b.m[2],1],[b.h[0],b.m[1],b.h[2],1],[b.h[0],b.m[1],b.m[2],1],[b.m[0],b.h[1],b.h[2],1],[b.m[0],b.h[1],b.m[2],1],[b.m[0],b.m[1],b.h[2],1],[b.m[0],b.m[1],b.m[2],1]],d=0;6>d;d++){for(var e=!0,g=0;8>g;g++)if(0<=s.rc.zc(a.ha[d],c[g])){e=!1;break}if(e)return!1}return!0}
h.update=function(){this.ka=s.c.create();s.c.multiply(s.na(2,s.P(-this.g[2])),s.na(0,s.P(-this.g[1]-90)),this.ka);s.c.multiply(this.ka,s.na(2,s.P(-this.g[0])),this.ka);s.c.multiply(this.ka,s.Fa(-this.a[0],-this.a[1],-this.a[2]),this.ka);this.$a=s.Zd(this.Dc,this.Na,this.Va,this.Ha);this.yb=s.c.create();s.c.multiply(this.$a,this.ka,this.yb);this.ha[0]=[0,0,1,1];this.ha[1]=[0,0,-1,1];this.ha[2]=[1,0,0,1];this.ha[3]=[-1,0,0,1];this.ha[4]=[0,1,0,1];this.ha[5]=[0,-1,0,1];var a=s.c.create();s.c.Ma(this.yb,
a);for(var b=0;6>b;b++)this.ha[b]=s.c.xb(a,this.ha[b]);this.B=!1};s.gd=function(a,b,c,d,e,g){var f=e.get(c);if(!f)return[d,c.k>=g];var k=w(a.p,c.k);d=(b[0]-c.q)/k;k=(b[1]-c.r)/k;d=s.fa(d,0,0.9999);var k=s.fa(k,0,0.9999),l=s.aa,m=d*(l-1),n=k*(l-1),p=Math.floor(m),q=Math.floor(n),r=f.L[q*l+p],t=f.L[(q+1)*l+p],m=m-p,r=r+(f.L[q*l+p+1]-r)*m,l=r+(t+(f.L[(q+1)*l+p+1]-t)*m-r)*(n-q),n=0,n=0.5>k?0.5>d?0:1:0.5>d?2:3;return!(f.O&1<<n)||c.k>=g?[l,!0]:s.gd(a,b,M(c,n),l,e,g)};s.gb=function(a,b,c,d){null==d&&(d=Number.MAX_VALUE);return s.gd(a,b,a.p.v,0,c,d)};
s.hd=function(a,b,c,d,e,g){var f=e.get(c);if(!f)return[d,c.k>=g];var k=w(a.p,c.k);d=(b[0]-c.q)/k;for(var k=(b[1]-c.r)/k,l=a.b,m=f.Qa(l.a,l.$d),n=0,p=s.aa,q=s.aa-1,r=0;1>=r;r++)for(var t=0;1>=t;t++){var v=[];s.c.Aa(m,[t,r,f.L[r*q*p+t*q]],v);L(l.f,v);v=f.o[r][t];v>n&&(n=v)}l=0;l=0.5>k?0.5>d?0:1:0.5>d?2:3;return!(f.O&1<<l)||c.k>=g?[n,!0]:s.hd(a,b,M(c,l),n,e,g)};s.Se=function(a,b,c,d){null==d&&(d=Number.MAX_VALUE);return s.hd(a,b,a.p.v,0,c,d)};
s.jd=function(a,b,c,d,e,g){var f=e.get(c);if(!f)return[d,c.k>=g];d=w(a.p,c.k);var k=(b[0]-c.q)/d,l=0,l=0.5>(b[1]-c.r)/d?0.5>k?0:1:0.5>k?2:3;return!(f.O&1<<l)||c.k>=g?[{te:c,Rd:f},!0]:s.jd(a,b,M(c,l),{te:c,Rd:f},e,g)};s.Te=function(a,b,c,d){null==d&&(d=Number.MAX_VALUE);return s.jd(a,b,a.p.v,{},c,d)};
s.Ue=function(a,b,c,d){var e=w(a.p,c.k);a=(b[0]-c.q)/e;c=(b[1]-c.r)/e;a=s.fa(a,0,0.9999);c=s.fa(c,0,0.9999);b=s.aa;var g=a*(b-1);a=c*(b-1);c=Math.floor(g);var e=Math.floor(a),f=d.L[e*b+c],k=d.L[(e+1)*b+c],g=g-c,f=f+(d.L[e*b+c+1]-f)*g;return f+(k+(d.L[(e+1)*b+c+1]-k)*g-f)*(a-e)};function Q(a,b,c){this.Q=a;this.G=null;this.s=b;this.xc=null;this.ub=null==c?!1:c}
function ua(a){a.G=document.createElement("canvas");if(null!=a.G&&(a.G.width=a.s[0],a.G.height=a.s[1],a.G.style.display="block",null!=a.G.getContext)){try{a.e=a.G.getContext("webgl",{preserveDrawingBuffer:a.ub})||a.G.getContext("experimental-webgl",{preserveDrawingBuffer:a.ub})}catch(b){}a.e&&(a.e.getExtension("OES_standard_derivatives"),a.Q.appendChild(a.G),a.e.tc=a.G.width,a.e.sc=a.G.height,a.e.clearColor(0,0,0,1),a.e.enable(a.e.DEPTH_TEST),a.e.viewport(0,0,a.e.tc,a.e.sc),a.e.clear(a.e.COLOR_BUFFER_BIT|
a.e.DEPTH_BUFFER_BIT))}}Q.prototype.resize=function(a,b){this.s=a;null!=this.G&&!0!=b&&(this.G.width=this.s[0],this.G.height=this.s[1]);null!=this.e&&(this.e.tc=this.G.width,this.e.sc=this.G.height)};Q.prototype.clear=function(){this.e.clear(this.e.DEPTH_BUFFER_BIT);this.e.enable(this.e.CULL_FACE)};
Q.prototype.useProgram=function(a,b,c,d){this.xc!=a&&(this.e.useProgram(a.$),this.xc=a,va(a),b=a.getAttribute(b),this.e.enableVertexAttribArray(b),null!=c&&(c=a.getAttribute(c),this.e.enableVertexAttribArray(c)),null!=d&&(a=a.getAttribute(d),this.e.enableVertexAttribArray(a)))};Q.prototype.bindTexture=function(a){!1!=a.hc&&(this.e.activeTexture(this.e.TEXTURE0),this.e.bindTexture(this.e.TEXTURE_2D,a.C))};s.Be=function(){return!0};
function wa(a,b){null!=b?a.e.bindFramebuffer(a.e.FRAMEBUFFER,b.Ec):(a.e.bindTexture(a.e.TEXTURE_2D,null),a.e.bindRenderbuffer(a.e.RENDERBUFFER,null),a.e.bindFramebuffer(a.e.FRAMEBUFFER,null))};function xa(a){a=this.e=a.e;if(null!=a){this.D=null;this.D=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,this.D);var b=[0,0,0,1,0,0,1,0,0,1,1,0,1,1,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0,1,1,0,1,1,1,1,1,1,1,0,1,1,0,1,1,0,0,1,0,0,0,0,0,1,1,0,0,1,0,1,1,1,0,1,1,1,0,1,0,0,1,1];a.bufferData(a.ARRAY_BUFFER,new Float32Array(b),a.STATIC_DRAW);this.D.ca=3;this.D.W=b.length/3;this.V=36}}xa.prototype.w=function(){this.e.deleteBuffer(this.D)};
xa.prototype.Oa=function(a,b){var c=this.e;if(null!=c){var d=a.getAttribute(b);c.bindBuffer(c.ARRAY_BUFFER,this.D);c.vertexAttribPointer(d,this.D.ca,c.FLOAT,!1,0,0);c.drawArrays(c.LINES,0,this.D.W)}};s.ua=null;
function R(a,b,c){this.i=b.i;this.e=a.e;this.nb=c;a=this.e;if(null!=a&&(this.ta=this.D=null,this.D=a.createBuffer(),a.bindBuffer(a.ARRAY_BUFFER,this.D),a.bufferData(a.ARRAY_BUFFER,new Float32Array(b.u),a.STATIC_DRAW),this.D.ca=3,this.D.W=b.u.length/3,this.ta=a.createBuffer(),a.bindBuffer(a.ARRAY_BUFFER,this.ta),a.bufferData(a.ARRAY_BUFFER,new Float32Array(b.A),a.STATIC_DRAW),this.ta.ca=2,this.ta.W=b.A.length/2,this.V=12*this.D.W+8*this.ta.W,this.Bb=this.D.W/3,null==s.ua)){b=Array(196605);for(c=0;196605>
c;c+=9)b[c]=1,b[c+1]=0,b[c+2]=0,b[c+3]=0,b[c+4]=1,b[c+5]=0,b[c+6]=0,b[c+7]=0,b[c+8]=1;s.ua=a.createBuffer();a.bindBuffer(a.ARRAY_BUFFER,s.ua);a.bufferData(a.ARRAY_BUFFER,new Float32Array(b),a.STATIC_DRAW);s.ua.ca=3;s.ua.W=b.length/3}}R.prototype.w=function(){this.e.deleteBuffer(this.D);this.e.deleteBuffer(this.ta)};
R.prototype.Oa=function(a,b,c,d){var e=this.e;if(null!=e){b=a.getAttribute(b);c=a.getAttribute(c);if(null!=d)var g=a.getAttribute(d);e.bindBuffer(e.ARRAY_BUFFER,this.D);e.vertexAttribPointer(b,this.D.ca,e.FLOAT,!1,0,0);e.bindBuffer(e.ARRAY_BUFFER,this.ta);e.vertexAttribPointer(c,this.ta.ca,e.FLOAT,!1,0,0);null!=d&&(e.bindBuffer(e.ARRAY_BUFFER,s.ua),e.vertexAttribPointer(g,s.ua.ca,e.FLOAT,!1,0,0));e.drawArrays(e.TRIANGLES,0,this.D.W)}};R.prototype.size=function(){return this.V};function S(a,b,c){this.e=a.e;this.$=null;this.pc=[];this.Jb=[];this.createProgram(b,c)}S.prototype.createShader=function(a,b){if(!a)return null;var c=this.e;if(null!=c){var d;d=!0!=b?c.createShader(c.FRAGMENT_SHADER):c.createShader(c.VERTEX_SHADER);c.shaderSource(d,a);c.compileShader(d);return c.getShaderParameter(d,c.COMPILE_STATUS)?d:(alert("An error occurred compiling the shaders: "+c.getShaderInfoLog(d)),null)}};
S.prototype.createProgram=function(a,b){var c=this.e;if(null!=c){var d=this.createShader(a,!0),e=this.createShader(b,!1),g=c.createProgram();c.attachShader(g,d);c.attachShader(g,e);c.linkProgram(g);c.getProgramParameter(g,c.LINK_STATUS)||alert("Unable to initialize the shader program.");c.useProgram(g);this.$=g}};function va(a){var b=a.e;null!=b&&null!=a.$&&(a=a.getUniform("uSampler"),null!=a&&b.uniform1i(a,0))}
function T(a,b,c){var d=a.e;null!=d&&null!=a.$&&(a=a.getUniform(b),null!=a&&d.uniformMatrix4fv(a,!1,c))}function U(a,b,c){var d=a.e;null!=d&&null!=a.$&&(a=a.getUniform(b),null!=a&&d.uniform1f(a,c))}S.prototype.getAttribute=function(a){var b=this.e;if(null!=b&&null!=this.$)return null==this.Jb[a]?(b=b.getAttribLocation(this.$,a),this.Jb[a]=b):this.Jb[a]};
S.prototype.getUniform=function(a){var b=this.e;if(null!=b&&null!=this.$)return null==this.pc[a]?(b=b.getUniformLocation(this.$,a),this.pc[a]=b):this.pc[a]};s.xd="attribute vec3 aPosition;\nuniform mat4 uMVP;\nvoid main(){ \ngl_Position = uMVP * vec4(aPosition, 1.0);\n}";s.vd="precision mediump float;\nvoid main() {\ngl_FragColor = vec4(0.0, 0.0, 1.0, 1.0);\n}";s.me="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMVP;\nvarying vec2 vTexCoord;\nvoid main(){ \ngl_Position = uMVP * vec4(aPosition, 1.0);\nvTexCoord = aTexCoord;\n}";s.le="precision mediump float;\nuniform sampler2D uSampler;\nvarying vec2 vTexCoord;\nconst vec4 gray = vec4(0.125, 0.125, 0.125, 1.0);\nvoid main() {\nfloat fade = smoothstep(0.51, 0.55, vTexCoord.t);\ngl_FragColor = mix(texture2D(uSampler, vTexCoord), gray, fade);\n}";
s.Md="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nuniform mat4 uGridMat;\nuniform float uGridStep1, uGridStep2;\nconst int HMSize = 5;\nconst float HMSize1 = float(HMSize-1);\nuniform float uHeight[HMSize*HMSize];\nvarying vec2 vTexCoord1;\nvarying vec2 vTexCoord2;\nvarying float vFogFactor;\nfloat round(float x) { return floor(x + 0.5); }\nvoid main() {\nvec3 pos = aPosition;\nfloat z = uHeight[int(round(pos.y*HMSize1)*float(HMSize) + round(pos.x*HMSize1))];\nvec4 camSpacePos = uMV * vec4(pos.xy, z, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvFogFactor = exp(uFogDensity * camDist);\nvec4 gridCoord = uGridMat * vec4(pos, 1.0);\nvTexCoord1 = aTexCoord;\nvTexCoord1 = gridCoord.xy * vec2(uGridStep1);\nvTexCoord2 = gridCoord.xy * vec2(uGridStep2);\n}";
s.Ld="precision mediump float;\nuniform sampler2D uSampler;\nuniform float uGridBlend;\nvarying vec2 vTexCoord1;\nvarying vec2 vTexCoord2;\nvarying float vFogFactor;\nconst vec4 fogColor = vec4(1, 1, 1, 1);\nvoid main() {\nvec4 gridColor = mix(texture2D(uSampler, vTexCoord1), texture2D(uSampler, vTexCoord2), uGridBlend);\ngl_FragColor = mix(fogColor, gridColor, vFogFactor);\n}";s.Kd="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nuniform mat4 uGridMat;\nuniform float uGridStep1, uGridStep2;\nconst int HMSize = 5;\nconst float HMSize1 = float(HMSize-1);\nuniform float uHeight[HMSize*HMSize];\nvarying vec2 vTexCoord1;\nvarying vec2 vTexCoord2;\nvarying float vDepth;\nfloat round(float x) { return floor(x + 0.5); }\nvoid main() {\nvec3 pos = aPosition;\nfloat z = uHeight[int(round(pos.y*HMSize1)*float(HMSize) + round(pos.x*HMSize1))];\nvec4 camSpacePos = uMV * vec4(pos.xy, z, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvDepth = camDist;\nvec4 gridCoord = uGridMat * vec4(pos, 1.0);\nvTexCoord1 = aTexCoord;\nvTexCoord1 = gridCoord.xy * vec2(uGridStep1);\nvTexCoord2 = gridCoord.xy * vec2(uGridStep2);\n}";
s.Jd="precision mediump float;\nuniform sampler2D uSampler;\nuniform float uGridBlend;\nvarying vec2 vTexCoord1;\nvarying vec2 vTexCoord2;\nvarying float vDepth;\nconst vec4 fogColor = vec4(1, 1, 1, 1);\nvoid main() {\ngl_FragColor = fract(vec4(1.0, 1.0/255.0, 1.0/65025.0, 1.0/16581375.0) * vDepth) + (-0.5/255.0);\n}";s.ue="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nvarying vec2 vTexCoord;\nvarying float vFogFactor;\nvoid main() {\nvec4 camSpacePos = uMV * vec4(aPosition, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvFogFactor = exp(uFogDensity * camDist);\nvTexCoord = aTexCoord;\n}";
s.se="precision mediump float;\nuniform sampler2D uSampler;\nvarying vec2 vTexCoord;\nvarying float vFogFactor;\nconst vec4 fogColor = vec4(1, 1, 1, 1);\nvoid main() {\ngl_FragColor = mix(fogColor, texture2D(uSampler, vTexCoord), vFogFactor);\n}";s.re="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nattribute vec3 aBarycentric;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nvarying vec2 vTexCoord;\nvarying vec3 vBarycentric;\nvarying float vFogFactor;\nvoid main() {\nvec4 camSpacePos = uMV * vec4(aPosition, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvFogFactor = exp(uFogDensity * camDist);\nvTexCoord = aTexCoord;\nvBarycentric = camSpacePos.xyz;\n}";
s.qe="precision mediump float;\n#extension GL_OES_standard_derivatives : enable\nuniform sampler2D uSampler;\nvarying vec2 vTexCoord;\nvarying vec3 vBarycentric;\nvarying float vFogFactor;\nvoid main() {\n#ifdef GL_OES_standard_derivatives\nvec3 nx = dFdx(vBarycentric);\nvec3 ny = dFdy(vBarycentric);\nvec3 normal=normalize(cross(nx,ny));\ngl_FragColor = vec4(vec3(max(0.0,normal.z*(204.0/255.0))+(32.0/255.0)),1.0);\n#else\ngl_FragColor = vec4(1.0,1.0,1.0,1.0);\n#endif\n}";s.od="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nattribute vec3 aBarycentric;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nvarying vec2 vTexCoord;\nvarying vec3 vBarycentric;\nvarying float vFogFactor;\nvoid main() {\nvec4 camSpacePos = uMV * vec4(aPosition, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvFogFactor = exp(uFogDensity * camDist);\nvTexCoord = aTexCoord;\nvBarycentric = aBarycentric;\n}";
s.we="precision mediump float;\n#extension GL_OES_standard_derivatives : enable\nuniform sampler2D uSampler;\nvarying vec2 vTexCoord;\nvarying vec3 vBarycentric;\nvarying float vFogFactor;\nconst vec4 fogColor = vec4(1, 1, 1, 1);\nfloat edgeFactor(){\n#ifdef GL_OES_standard_derivatives\nvec3 d = fwidth(vBarycentric);\nvec3 a3 = smoothstep(vec3(0.0), d*1.0, vBarycentric);\nreturn min(min(a3.x, a3.y), a3.z);\n#else\nfloat a = min(min(vBarycentric.x, vBarycentric.y), vBarycentric.z);\nreturn a > 0.1 ? 1.0 : smoothstep(0.0,1.0,a*10.0);\n#endif\n}\nvoid main() {\ngl_FragColor = mix(fogColor, vec4( mix(vec3(0.0), texture2D(uSampler, vTexCoord).rgb, edgeFactor()) , 1.0), vFogFactor);\n}";
s.ve="precision mediump float;\n#extension GL_OES_standard_derivatives : enable\nuniform sampler2D uSampler;\nvarying vec2 vTexCoord;\nvarying vec3 vBarycentric;\nvarying float vFogFactor;\nconst vec4 fogColor = vec4(1, 1, 1, 1);\nfloat edgeFactor(){\n#ifdef GL_OES_standard_derivatives\nvec3 d = fwidth(vBarycentric);\nvec3 a3 = smoothstep(vec3(0.0), d*1.0, vBarycentric);\nreturn min(min(a3.x, a3.y), a3.z);\n#else\nfloat a = min(min(vBarycentric.x, vBarycentric.y), vBarycentric.z);\nreturn a > 0.1 ? 1.0 : smoothstep(0.0,1.0,a*10.0);\n#endif\n}\nvoid main() {\ngl_FragColor = vec4( mix(vec3(0.0), vec3(0.5), edgeFactor()) , 1.0);\n}";
s.pe="attribute vec3 aPosition;\nattribute vec2 aTexCoord;\nuniform mat4 uMV, uProj;\nuniform float uFogDensity;\nvarying vec2 vTexCoord;\nvarying float vDepth;\nvoid main() {\nvec4 camSpacePos = uMV * vec4(aPosition, 1.0);\ngl_Position = uProj * camSpacePos;\nfloat camDist = length(camSpacePos.xyz);\nvDepth = camDist;\nvTexCoord = aTexCoord;\n}";s.oe="precision mediump float;\nuniform sampler2D uSampler;\nvarying float vDepth;\nvoid main() {\ngl_FragColor = fract(vec4(1.0, 1.0/255.0, 1.0/65025.0, 1.0/16581375.0) * vDepth) + (-0.5/255.0);\n}";
s.Od="\nattribute vec4 aPosition;\nuniform mat4 uProjectionMatrix;\nuniform mat4 uData;\nuniform vec4 uColor;\nuniform float uDepth;\nvarying vec4 vColor;\nvarying vec2 vTexcoords;\nvoid main(void){\nint i=int(aPosition.x);\nif(i==0) gl_Position=uProjectionMatrix*vec4(floor(uData[0][0]+0.1),floor(uData[0][1]+0.1),uDepth,1.0), vTexcoords=vec2(uData[0][2], uData[0][3]);\nif(i==1) gl_Position=uProjectionMatrix*vec4(floor(uData[1][0]+0.1),floor(uData[1][1]+0.1),uDepth,1.0), vTexcoords=vec2(uData[1][2], uData[1][3]);\nif(i==2) gl_Position=uProjectionMatrix*vec4(floor(uData[2][0]+0.1),floor(uData[2][1]+0.1),uDepth,1.0), vTexcoords=vec2(uData[2][2], uData[2][3]);\nif(i==3) gl_Position=uProjectionMatrix*vec4(floor(uData[3][0]+0.1),floor(uData[3][1]+0.1),uDepth,1.0), vTexcoords=vec2(uData[3][2], uData[3][3]);\nvec4 c=uColor*(1.0/255.0);\nc.w*=1.0;\nvColor=c;\n}";
s.Nd="precision mediump float;\nvarying vec4 vColor;\nvarying vec2 vTexcoords;\nuniform sampler2D uSampler;\nvoid main(void){\nvec4 c=texture2D(uSampler, vec2(vTexcoords.x, vTexcoords.y) );\nc*=vColor;\ngl_FragColor = c;\n}";function V(a,b,c,d){this.j=a;this.e=a.e;this.Ec=this.C=null;this.V=0;this.nb=d;this.ac=this.uc=0;this.M=null;this.hc=!1;this.d=c;null!=b&&this.load(b)}V.prototype.w=function(){this.e.deleteTexture(this.C)};V.prototype.size=function(){return this.V};
function ya(a,b,c,d,e,g){var f=a.e;a.C=f.createTexture();f.bindTexture(f.TEXTURE_2D,a.C);g=!0==g?f.REPEAT:f.CLAMP_TO_EDGE;f.texParameteri(f.TEXTURE_2D,f.TEXTURE_WRAP_S,g);f.texParameteri(f.TEXTURE_2D,f.TEXTURE_WRAP_T,g);g=!1;switch(e){case "linear":f.texParameteri(f.TEXTURE_2D,f.TEXTURE_MIN_FILTER,f.LINEAR);f.texParameteri(f.TEXTURE_2D,f.TEXTURE_MAG_FILTER,f.LINEAR);break;case "trilinear":f.texParameteri(f.TEXTURE_2D,f.TEXTURE_MIN_FILTER,f.LINEAR_MIPMAP_LINEAR);f.texParameteri(f.TEXTURE_2D,f.TEXTURE_MAG_FILTER,
f.LINEAR);g=!0;break;default:f.texParameteri(f.TEXTURE_2D,f.TEXTURE_MIN_FILTER,f.NEAREST),f.texParameteri(f.TEXTURE_2D,f.TEXTURE_MAG_FILTER,f.NEAREST)}f.pixelStorei(f.UNPACK_ALIGNMENT,1);f.texImage2D(f.TEXTURE_2D,0,f.RGBA,b,c,0,f.RGBA,f.UNSIGNED_BYTE,d);!0==g&&f.generateMipmap(f.TEXTURE_2D);f.bindTexture(f.TEXTURE_2D,null);a.uc=b;a.ac=c;a.V=b*c*4;a.hc=!0}
function za(a,b,c){var d=a.e;a.C=d.createTexture();d.bindTexture(d.TEXTURE_2D,a.C);c=!0==c?d.REPEAT:d.CLAMP_TO_EDGE;d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_S,c);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_WRAP_T,c);c=!1;switch("linear"){case "linear":d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.LINEAR);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MAG_FILTER,d.LINEAR);break;case "trilinear":d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.LINEAR_MIPMAP_LINEAR);d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MAG_FILTER,
d.LINEAR);c=!0;break;default:d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MIN_FILTER,d.NEAREST),d.texParameteri(d.TEXTURE_2D,d.TEXTURE_MAG_FILTER,d.NEAREST)}!0!=s.Tc&&(d.texImage2D(d.TEXTURE_2D,0,d.RGBA,d.RGBA,d.UNSIGNED_BYTE,b),!0==c&&d.generateMipmap(d.TEXTURE_2D));d.bindTexture(d.TEXTURE_2D,null);a.uc=b.naturalWidth;a.ac=b.naturalHeight;a.V=b.naturalWidth*b.naturalHeight*4;a.hc=!0}
V.prototype.load=function(a,b,c){this.M=new Image;this.M.crossOrigin="anonymous";this.M.onload=function(){if(null==this.d||!0!=this.d.t)za(this,this.M,!1),this.M=null}.bind(this);this.M.onerror=function(){null!=this.d&&!0==this.d.t||null==c||c()}.bind(this);this.M.src=a};
V.prototype.createFramebuffer=function(a,b){if(null!=this.C){var c=this.e,d=c.createFramebuffer();c.bindFramebuffer(c.FRAMEBUFFER,d);d.width=a;d.height=b;c.bindTexture(c.TEXTURE_2D,this.C);var e=c.createRenderbuffer();c.bindRenderbuffer(c.RENDERBUFFER,e);c.renderbufferStorage(c.RENDERBUFFER,c.DEPTH_COMPONENT16,a,b);c.framebufferTexture2D(c.FRAMEBUFFER,c.COLOR_ATTACHMENT0,c.TEXTURE_2D,this.C,0);c.framebufferRenderbuffer(c.FRAMEBUFFER,c.DEPTH_ATTACHMENT,c.RENDERBUFFER,e);c.bindTexture(c.TEXTURE_2D,
null);c.bindRenderbuffer(c.RENDERBUFFER,null);c.bindFramebuffer(c.FRAMEBUFFER,null);this.Ec=d}};function Aa(a,b){this.j=a;this.H=new R(a,b.H);this.C=new V(a);za(this.C,b.M);this.Nc=b.Nc;this.Lc=b.Lc}Aa.prototype.w=function(){this.H.w();this.C.w()};Aa.prototype.size=function(){return this.H.size()+this.C.size()};function Ba(a,b){this.j=a;this.J=new ma(b)}Ba.prototype.get=function(a,b){var c=this.J.find(a);if(c)return c;c=new Aa(this.j,b);na(this.J,a,c,c.size());return c};Ba.prototype.size=function(){return this.J.sa};Ba.prototype.reset=function(){return this.J.clear()};function W(){this.u=[];this.A=[];this.i=new ka;this.nb=this.V=0}W.prototype.w=function(){this.u=[];this.A=[];this.i=null};
W.prototype.load=function(a,b,c){s.Mc(a,function(a){this.nb=a.byteLength;for(var c=0,g=1/65535,f="",k=0;8>k;k++)f+=String.fromCharCode(a.getUint8(c,!0)),c+=1;if("BIN.MESH"==f&&(k=a.getUint32(c,!0),c+=4,!(1<k))){for(k=0;3>k;k++)this.i.h[k]=a.getFloat64(c,!0),c+=8;for(k=0;3>k;k++)this.i.m[k]=a.getFloat64(c,!0),c+=8;for(var f=a.getUint16(c,!0),c=c+2,l=Array(3*f),m=0;m<f;m++)k=3*m,l[k]=a.getUint16(c,!0),c+=2,l[k+1]=a.getUint16(c,!0),c+=2,l[k+2]=a.getUint16(c,!0),c+=2;for(var f=a.getUint16(c,!0),c=c+2,
n=Array(2*f),m=0;m<f;m++)k=2*m,n[k]=a.getUint16(c,!0),c+=2,n[k+1]=65535-a.getUint16(c,!0),c+=2;f=a.getUint16(c,!0);c+=2;this.u=Array(9*f);this.A=Array(6*f);for(m=0;m<f;m++){for(k=0;3>k;k++){var p=3*a.getUint16(c,!0),c=c+2,q=9*m+3*k;this.u[q]=l[p]*g;this.u[q+1]=l[p+1]*g;this.u[q+2]=l[p+2]*g}for(k=0;3>k;k++)p=2*a.getUint16(c,!0),c+=2,q=6*m+2*k,this.A[q]=n[p]*g,this.A[q+1]=n[p+1]*g}this.V=8*(this.u.length+this.A.length)+56;null!=b&&b()}}.bind(this),function(){null!=c&&c()}.bind(this))};
W.prototype.size=function(){return this.V};W.prototype.fileSize=function(){return this.nb};s.Fb=function(a,b){b*=Math.PI;a=2*a*Math.PI;return[Math.cos(a)*Math.sin(b)*0.5+0.5,Math.sin(a)*Math.sin(b)*0.5+0.5,0.5*Math.cos(b)+0.5]};s.aa=5;
function Ca(a,b,c,d){this.d=a;this.i=new ka;this.o=[];this.L=[];this.O=0;this.eb=[];for(var e=0;2>e;e++)this.o[e]=[];a=c.kb;var g=a.getInt16(c.l,!0);c.l+=2;e=a.getInt16(c.l,!0);c.l+=2;this.i.h[0]=b.q;this.i.h[1]=b.r;this.i.h[2]=g;g=w(this.d.p,b.k);this.i.m[0]=b.q+g;this.i.m[1]=b.r+g;this.i.m[2]=e;if(2<d){for(e=0;2>e;e++)for(b=0;2>b;b++)this.o[e][b]=s.yc(a.getUint16(c.l,!0)),c.l+=2;s.yc(a.getUint16(c.l,!0));c.l+=2;a.getUint16(c.l,!0);c.l+=2}else for(e=0;2>e;e++)for(b=0;2>b;b++)this.o[e][b]=a.getFloat32(c.l,
!0),c.l+=4;if(1<d)for(d=a.getInt16(c.l,!0),c.l+=2,b=a.getInt16(c.l,!0),c.l+=2,e=0,g=s.aa*s.aa;e<g;e++)this.L[e]=d+(a.getInt16(c.l,!0)+32768)*((b-d)/65535),c.l+=2;else for(e=0,g=s.aa*s.aa;e<g;e++)this.L[e]=a.getInt16(c.l,!0),c.l+=2;for(e=0;4>e;e++)this.eb[e]=null;this.O=0}
Ca.prototype.Qa=function(a,b){var c=b;null!=c?(c[0]=y(this.i,0),c[1]=0,c[2]=0,c[3]=0,c[4]=0,c[5]=y(this.i,1),c[6]=0,c[7]=0,c[8]=0,c[9]=0,c[10]=1,c[11]=0,c[12]=this.i.h[0]-a[0],c[13]=this.i.h[1]-a[1],c[14]=0,c[15]=1):(c=s.c.create(),s.c.multiply(s.Fa(this.i.h[0]-a[0],this.i.h[1]-a[1],0),s.Eb(y(this.i,0),y(this.i,1),1),c));return c};
function Da(a,b,c){null!=c&&(c[0]=y(a.i,0),c[1]=0,c[2]=0,c[3]=0,c[4]=0,c[5]=y(a.i,1),c[6]=0,c[7]=0,c[8]=0,c[9]=0,c[10]=y(a.i,2),c[11]=0,c[12]=a.i.h[0]-b[0],c[13]=a.i.h[1]-b[1],c[14]=a.i.h[2],c[15]=1);return c}Ca.prototype.size=function(){for(var a=308,b=0;4>b;b++)null!=this.eb[b]&&(a+=this.eb[b].size());return a};
function Ea(a,b,c){this.F=b;this.d=a;a="";for(var d=0;8>d;d++)a+=String.fromCharCode(c.kb.getUint8(c.l,!0)),c.l+=1;"METATILE"==a&&(a=c.kb.getUint32(c.l,!0),c.l+=4,3<a||(this.pd=Fa(this,b,c,a)))}Ea.prototype.w=function(){};function Fa(a,b,c,d){var e=new Ca(a.d,b,c,d),g=c.kb.getUint8(c.l,!0);c.l+=1;for(var f=0;4>f;f++)g&1<<f+4&&(e.eb[f]=Fa(a,M(b,f),c,d));e.O=g&15;return e}Ea.prototype.size=function(){return this.pd.size()};
s.rd=function(a,b,c,d){this.d=a;this.F=b;this.Ya=c;this.Xa=d;this.Td=function(b){!0!=this.d.t&&null!=this.Ya&&(b=new Ea(a,this.F,{kb:b,l:0}),this.Ya(this.F,b))}.bind(this);this.Sd=function(){!0!=this.d.t&&null!=this.Xa&&this.Xa(this.F)}.bind(this);s.Mc(da(this.d.p,this.F),this.Td,this.Sd)};
function Ga(a,b,c,d,e){this.d=a;this.R=new pa(a,b,c,d,e);this.contains=this.R.contains.bind(this.R);this.trim=this.R.trim.bind(this.R);this.reset=this.R.reset.bind(this.R);this.ic=this.R.ic.bind(this.R);this.update=this.R.update.bind(this.R);this.size=this.R.size.bind(this.R)}
Ga.prototype.get=function(a){for(var b=a,c=this.d.p;Math.abs(b.k-c.Rc)%c.Qc&&b.k>c.v.k;)b=b.parent();if(b=this.R.get(b)){for(var c=new u(b.d,b.F.k,b.F.q,b.F.r),d=b.pd;c.k<a.k;){var e=w(b.d.p,c.k),g=c.q+e/2,e=c.r+e/2,f=0;Math.round(a.q)>=Math.round(g)&&(f|=1,c.q=g);Math.round(a.r)>=Math.round(e)&&(f|=2,c.r=e);c.k++;(d=d.eb[f])||console.log("Missing tile metadata")}!c.isEqual(a)&&console.log("Metatile inconsistency");a=d}else a=null;return a};s.Db=1.1;s.kd=0.7;s.Tc=!1;
function Ha(a,b,c,d){this.d=a;this.$c=this.ad=this.Za=this.Yc=this.Zc=null;this.Q=b;this.Wc=c;this.Ba=this.t=!1;a=this.Q.getBoundingClientRect();this.s=[a.width,a.height];this.hb=!1;this.B=this.Ic=!0;this.Qd=1;this.wc=this.K=this.d.n.K;this.ea=0.5*this.d.n.ea;this.Y=0;this.va=[0,1,0];this.oc=this.d.p.ne*s.kd;this.zb=!0;this.j=new Q(b,this.s,d);this.f=new qa(this,this.d.n.vc,2,this.d.n.ib);this.a=[this.d.p.mb[0],this.d.p.mb[1],this.d.p.mb[2]];this.g=[this.d.p.lb[0],this.d.p.lb[1],this.d.p.lb[2]];this.T=
new Ga(this.d,Number.MAX_VALUE,function(){this.B=!0}.bind(this),this.d.n.Wa,s.rd);this.oa=new s.sd(this.d,Number.MAX_VALUE,function(){this.B=!0}.bind(this),this.d.n.Wa,s.td);this.$b=new Ba(this.j,this.d.n.Fc);this.ya=this.Ea=this.cb=this.Sa=this.Ra=null;this.Ta=this.d.n.Jc;this.Hb=!0;this.ec=this.ab=this.bb=this.bd=null;this.Ub=this.Tb=this.Rb=this.Ob=this.bc=!1;this.Pa=0;this.Vb=this.Sb=this.Pb=this.Qb=!1;this.qd=!0;this.fd=document.getElementById("vadstena-engine-render-stats");this.Cb=this.cd=
this.ra=this.kc=this.lc=this.Gb=this.fb=0;this.Ja=[];this.fc=null;this.qb=this.rb=this.sb=this.Zb=0;this.Wb=s.c.create();this.Bc=s.c.create();this.Ad=[0,0,0];this.Cc=s.c.create();this.$d=s.c.create();this.Ga=s.c.create();this.ee=[0,0,0];this.de=[[3,1,2,0],[3,2,1,0],[2,3,0,1],[2,0,3,1],[0,2,1,3],[0,1,2,3],[1,0,3,2],[1,3,0,2]];this.vb=[0,0,100];this.Ua=null;window.addEventListener("resize",this.Vc.bind(this),!1);ua(this.j);this.Zc=new S(this.j,s.ue,s.se);this.ad=new S(this.j,s.od,s.we);this.$c=new S(this.j,
s.od,s.ve);this.ce=new S(this.j,s.re,s.qe);this.Yc=new S(this.j,s.Md,s.Ld);this.Za=new S(this.j,s.me,s.le);this.be=new S(this.j,s.pe,s.oe);this.ae=new S(this.j,s.Kd,s.Jd);this.jc=new S(this.j,s.xd,s.vd);this.Da=new S(this.j,s.Od,s.Nd);Ia(this);Ja(this);Ka(this);La(this);Ma(this);this.wd=new xa(this.j);Na(this,this.s[0],this.s[1]);window.dd(this.update.bind(this))}h=Ha.prototype;h.Vc=function(){if(!0!=this.t){var a=this.Q.getBoundingClientRect();Na(this,a.width,a.height)}};
h.w=function(){!0!=this.t&&(this.t=!0,this.T.reset(),this.oa.reset(),this.$b.reset(),null!=this.Ra&&this.Ra.w(),null!=this.Sa&&this.Sa.w(),null!=this.cb&&this.cb.w(),null!=this.Ea&&this.Ea.w(),null!=this.ya&&this.ya.w(),this.Q.removeChild(this.j.G))};
function Ia(a){var b=new W,c=s.aa;c--;for(var d=0;d<c;d++)for(var e=0;e<c;e++){var g=e/c,f=(e+1)/c,k=d/c,l=(d+1)/c;b.u.push(g,k,0);b.u.push(f,k,0);b.u.push(f,l,0);b.A.push(g,k);b.A.push(f,k);b.A.push(f,l);b.u.push(f,l,0);b.u.push(g,l,0);b.u.push(g,k,0);b.A.push(f,l);b.A.push(g,l);b.A.push(g,k)}b.i.h[0]=b.i.h[1]=b.i.h[2]=0;b.i.m[0]=b.i.m[1]=b.i.m[2]=1;b.V=8*(b.u.length+b.A.length)+56;a.Ra=new R(a.j,b);b=new Uint8Array(16384);for(c=0;64>c;c++)for(d=0;64>d;d++)e=4*(64*c+d),1>c||63<=c||1>d||63<=d?(b[e]=
255,b[e+1]=255,b[e+2]=255):(b[e]=32,b[e+1]=32,b[e+2]=32),b[e+3]=255;a.Sa=new V(a.j);ya(a.Sa,64,64,b,"trilinear",!0)}function Ka(a){var b=a.Ta,c=new Uint8Array(b*b*4);a.ya=new V(a.j);ya(a.ya,b,b,c);a.ya.createFramebuffer(b,b);for(var b=16,c=new Uint8Array(b*b*4),d=0;d<b;d++)for(var e=0;e<b;e++){var g=4*(d*b+e);c[g]=255;c[g+1]=0;c[g+2]=0;c[g+3]=255}a.bd=new V(a.j);ya(a.bd,b,b,c)}
function La(a){var b=new Uint8Array(2048),c="............................................................ xxx..x..xxx.xxx.x...xxx.xxx.xxx.xxx.xxx..................... x.x.xx....x...x.x...x...x.....x.x.x.x.x......x.............. x.x..x..xxx.xxx.x...xxx.xxx...x.xxx.xxx.........x.x......... x.x..x..x.....x.xxx...x.x.x...x.x.x...x......x...x.......... xxx..x..xxx.xxx..x..xxx.xxx...x.xxx.xxx..x......x.x......... ............................................................".split(" ");a.ld={0:0,1:4,2:8,
3:12,4:16,5:20,6:24,7:28,8:32,9:36,".":40,":":44,x:48,y:52," ":56};for(var b=new Uint8Array(2048),d=0;8>d;d++)for(var e=0;64>e;e++){var g=4*(64*d+e);b[g]=0;b[g+1]=0;b[g+2]=0;b[g+3]=255}for(var d=0,f=c.length;d<f;d++)for(var k=c[d],e=0,l=k.length;e<l;e++)g=4*(64*d+e),"."!=k.charAt(e)&&(b[g]=255,b[g+1]=255,b[g+2]=255);a.md=new V(a.j);ya(a.md,64,8,b)}
function Ma(a){var b=a.j.e;a.bb=b.createBuffer();b.bindBuffer(b.ARRAY_BUFFER,a.bb);b.bufferData(b.ARRAY_BUFFER,new Float32Array([0,0,0,1,1,0,0,1,2,0,0,1,3,0,0,1]),b.STATIC_DRAW);a.bb.ca=4;a.bb.W=4;a.ab=b.createBuffer();b.bindBuffer(b.ELEMENT_ARRAY_BUFFER,a.ab);b.bufferData(b.ELEMENT_ARRAY_BUFFER,new Uint16Array([0,1,2,0,2,3]),b.STATIC_DRAW);a.ab.ca=1;a.ab.W=6}
function Ja(a){for(var b=new W,c=0;32>c;c++)for(var d=0;64>d;d++){var e=b,g=d/64,f=c/32,k=(d+1)/64,l=(c+1)/32,m=s.Fb(g,f),n=[g,f],p=s.Fb(g,l),g=[g,l],q=s.Fb(k,f),f=[k,f],r=s.Fb(k,l),k=[k,l];e.u.push(p[0],p[1],p[2]);e.u.push(m[0],m[1],m[2]);e.u.push(q[0],q[1],q[2]);e.A.push(g[0],g[1]);e.A.push(n[0],n[1]);e.A.push(f[0],f[1]);e.u.push(q[0],q[1],q[2]);e.u.push(r[0],r[1],r[2]);e.u.push(p[0],p[1],p[2]);e.A.push(f[0],f[1]);e.A.push(k[0],k[1]);e.A.push(g[0],g[1]);e.V=8*(e.u.length+e.A.length)+56}b.i.h[0]=
b.i.h[1]=b.i.h[2]=0;b.i.m[0]=b.i.m[1]=b.i.m[2]=1;a.cb=new R(a.j,b);a.Ea=new V(a.j,a.d.n.Ea,a.d)}function Na(a,b,c){var d=a.f;d.Na=b/c;d.B=!0;a.s=[b,c];a.j.resize(a.s,void 0);Oa(a);d=[];d[0]=2/b;d[1]=0;d[2]=0;d[3]=0;d[4]=0;d[5]=-2/c;d[6]=0;d[7]=0;d[8]=0;d[9]=0;d[10]=1;d[11]=0;d[12]=0.5*-b*d[0];d[13]=0.5*-c*d[5];d[14]=0;d[15]=1;a.ec=d}function Pa(a,b){var c=Math.log(0.05)/(10*a.d.n.ib*(Math.max(5,-a.g[1])/90));U(b,"uFogDensity",c)}
function Qa(a,b,c,d){null==a.Ja[b.k]?a.Ja[b.k]=1:a.Ja[b.k]++;if(null!=a.Ua){var e=w(a.d.p,b.k);a.Ua[0]>b.q&&a.Ua[0]<b.q+e&&a.Ua[1]>b.r&&a.Ua[1]<b.r+e&&console.log("tile-hit: x:"+b.q+" y: "+b.r+" lod: "+b.k)}if(c&&!a.bc){var g=a.$b.get(b,c),e=null;if(!0==a.Ba)e=a.be;else switch(a.Pa){default:e=a.Zc;break;case 1:e=a.ad;break;case 2:e=a.$c;break;case 3:e=a.ce}a.j.useProgram(e,"aPosition","aTexCoord",!0==a.Pa?"aBarycentric":null);var f=a.Wb;s.c.multiply(ra(a.f),c.Qa(a.a,a.Cc),f);c=K(a.f);T(e,"uMV",f);
T(e,"uProj",c);Pa(a,e);a.j.bindTexture(g.C);g.H.Oa(e,"aPosition","aTexCoord",!0==a.Pa?"aBarycentric":null);if(!0!=a.Ba&&(a.sb+=g.H.size()+g.C.size(),a.rb+=g.C.size(),a.qb+=g.H.size(),a.lc++,a.ra+=g.H.Bb,!0==a.Ob)){a.j.useProgram(a.jc,"aPosition");e=s.c.create();s.c.multiply(c,f,e);f=a.Wb;s.c.multiply(ra(a.f),Da(d,a.a,a.Cc),f);c=K(a.f);s.c.multiply(c,f,e);T(a.jc,"uMVP",e);a.wd.Oa(a.jc,"aPosition");e=d.i.h;f=d.i.m;c=a.qa([e[0]+0.5*(f[0]-e[0]),e[1]+0.5*(f[1]-e[1]),f[2]]);if(!0==a.Tb){var k=""+b.q+" "+
b.r;X(a,Math.round(c[0]-2*k.length),Math.round(c[1]-11),k,[0,255,255,255],c[2])}!0==a.Vb&&(k=""+g.C.uc+" x "+g.C.ac,X(a,Math.round(c[0]-2*k.length),Math.round(c[1]-18),k,[255,255,255,255],c[2]));!0==a.Rb&&(k=""+b.k,X(a,Math.round(c[0]-2*k.length),Math.round(c[1]-4),k,[255,0,0,255],c[2]));!0==a.Qb&&(k=""+g.H.Bb,X(a,Math.round(c[0]-2*k.length),Math.round(c[1]+3),k,[0,255,0,255],c[2]));!0==a.Pb&&(b=Ra(a,d,!0),k=""+b[1].toFixed(2)+" "+b[0].toFixed(2),X(a,Math.round(c[0]-2*k.length),Math.round(c[1]+10),
k,[255,0,255,255],c[2]));!0==a.Ub&&(c=a.qa([e[0]+0.1*(f[0]-e[0]),e[1]+0.1*(f[1]-e[1]),f[2]]),k=""+d.o[0][0].toFixed(3),X(a,Math.round(c[0]-2*k.length),Math.round(c[1]-4),k,[255,255,0,255],c[2]),c=a.qa([e[0]+0.9*(f[0]-e[0]),e[1]+0.1*(f[1]-e[1]),f[2]]),k=""+d.o[0][1].toFixed(3),X(a,Math.round(c[0]-2*k.length),Math.round(c[1]-4),k,[255,255,0,255],c[2]),c=a.qa([e[0]+0.9*(f[0]-e[0]),e[1]+0.9*(f[1]-e[1]),f[2]]),k=""+d.o[1][1].toFixed(3),X(a,Math.round(c[0]-2*k.length),Math.round(c[1]-4),k,[255,255,0,255],
c[2]),c=a.qa([e[0]+0.1*(f[0]-e[0]),e[1]+0.9*(f[1]-e[1]),f[2]]),k=""+d.o[1][0].toFixed(3),X(a,Math.round(c[0]-2*k.length),Math.round(c[1]-4),k,[255,255,0,255],c[2]))}}else e=!0==a.Ba?a.ae:a.Yc,a.j.useProgram(e,"aPosition","aTexCoord"),f=a.Wb,s.c.multiply(ra(a.f),d.Qa(a.a,a.Bc),f),T(e,"uMV",f),T(e,"uProj",K(a.f)),b=a.Bc,d.Qa(ia(a.d.p,a.a,a.Ad),b),T(e,"uGridMat",b),Pa(a,e),b=a.d.n.Gc,g=a.d.n.Hc,f=s.aa,f=Math.max(10,a.f.a[2]-0.25*(d.L[0]+d.L[f-1]+d.L[(f-1)*f]+d.L[(f-1)*f+f-1])+20),f=Math.log(f)/Math.log(b),
c=Math.pow(b,Math.ceil(f)),k=f-Math.floor(f),U(e,"uGridStep1",g/Math.pow(b,Math.floor(f))),U(e,"uGridStep2",g/c),U(e,"uGridBlend",k),d=d.L,b=e.e,null!=b&&null!=e.$&&(g=e.getUniform("uHeight"),null!=g&&b.uniform1fv(g,d)),a.j.bindTexture(a.Sa),a.Ra.Oa(e,"aPosition","aTexCoord"),!0!=a.Ba&&(a.kc++,a.ra+=a.Ra.Bb)}
function Sa(a){var b=s.c.create();s.c.multiply(s.Eb(2,2,2),s.Fa(-0.5,-0.5,-0.5),b);var c=s.c.create();s.c.multiply(s.Fa(a.f.ia()[0],a.f.ia()[1],a.f.ia()[2]-400),s.fe(0.9*a.f.Ha),c);var d=s.c.create();s.c.multiply(sa(a.f),c,d);s.c.multiply(d,b,d);a.j.useProgram(a.Za,"aPosition","aTexCoord");a.j.bindTexture(a.Ea);va(a.Za);T(a.Za,"uMVP",d);a.cb.Oa(a.Za,"aPosition","aTexCoord");a.ra+=a.cb.Bb}
function X(a,b,c,d,e,g){if(null!=a.ec){var f=a.j.e;f.disable(f.CULL_FACE);f.enable(f.DEPTH_TEST);null==g&&f.disable(f.DEPTH_TEST);a.j.useProgram(a.Da,"aPosition",null);a.j.bindTexture(a.md);var k=a.bb;f.bindBuffer(f.ARRAY_BUFFER,k);f.vertexAttribPointer(a.Da.getAttribute("aPosition"),k.ca,f.FLOAT,!1,0,0);k=a.ab;f.bindBuffer(f.ELEMENT_ARRAY_BUFFER,k);T(a.Da,"uProjectionMatrix",a.ec);var l=a.Da,m=l.e;null!=m&&null!=l.$&&(l=l.getUniform("uColor"),null!=l&&m.uniform4fv(l,e));U(a.Da,"uDepth",null!=g?g:
0);e=b;m=0;for(l=d.length;m<l;m++){var n=a.ld[d.charAt(m)];T(a.Da,"uData",[b,c,0.015625*n,0,b+4,c,0.015625*(n+4),0,b+4,c+7,0.015625*(n+4),0.875,b,c+7,0.015625*n,0.875]);f.drawElements(f.TRIANGLES,k.W,f.UNSIGNED_SHORT,0);b+=4}b=e-1;n=a.ld[" "];T(a.Da,"uData",[b,c,0.015625*n,0,b+4,c,0.015625*(n+4),0,b+4,c+7,0.015625*(n+4),0.875,b,c+7,0.015625*n,0.875]);f.drawElements(f.TRIANGLES,k.W,f.UNSIGNED_SHORT,0);f.enable(f.CULL_FACE);null==g&&f.enable(f.DEPTH_TEST)}}
function Ra(a,b,c){var d=a.s[0]/2,e=Ta(a),g=b.i.m[0]-b.i.h[0],f=[b.i.h[0],b.i.h[1],b.i.h[2]],k=[f[0]+g,f[1],f[2]],l=[f[0]+g,f[1]+g,f[2]],m=[f[0],f[1]+g,f[2]],n=b.i.h[2],p=b.i.m[2],q=0,r=0;e[1]<f[1]?e[0]<f[0]?(r=b.o[0][0],q=e[2]>p?L(a.f,[f[0]-a.a[0],f[1]-a.a[1],p],c):e[2]<n?L(a.f,[f[0]-a.a[0],f[1]-a.a[1],n],c):L(a.f,[f[0]-a.a[0],f[1]-a.a[1],e[2]],c)):e[0]>k[0]?(r=b.o[0][1],q=e[2]>p?L(a.f,[k[0]-a.a[0],k[1]-a.a[1],p],c):e[2]<n?L(a.f,[k[0]-a.a[0],k[1]-a.a[1],n],c):L(a.f,[k[0]-a.a[0],k[1]-a.a[1],e[2]],
c)):(r=b.o[0][0]+(e[0]-f[0])/g*(b.o[0][1]-b.o[0][0]),q=e[2]>p?L(a.f,[e[0]-a.a[0],k[1]-a.a[1],p],c):e[2]<n?L(a.f,[e[0]-a.a[0],k[1]-a.a[1],n],c):L(a.f,[e[0]-a.a[0],k[1]-a.a[1],e[2]],c)):e[1]>m[1]?e[0]<m[0]?(r=b.o[1][0],q=e[2]>p?L(a.f,[m[0]-a.a[0],m[1]-a.a[1],p],c):e[2]<n?L(a.f,[m[0]-a.a[0],m[1]-a.a[1],n],c):L(a.f,[m[0]-a.a[0],m[1]-a.a[1],e[2]],c)):e[0]>l[0]?(r=b.o[1][1],q=e[2]>p?L(a.f,[l[0]-a.a[0],l[1]-a.a[1],p],c):e[2]<n?L(a.f,[l[0]-a.a[0],l[1]-a.a[1],n],c):L(a.f,[l[0]-a.a[0],l[1]-a.a[1],e[2]],c)):
(r=b.o[1][0]+(e[0]-m[0])/g*(b.o[1][1]-b.o[0][1]),q=e[2]>p?L(a.f,[e[0]-a.a[0],k[1]-a.a[1],p],c):e[2]<n?L(a.f,[e[0]-a.a[0],k[1]-a.a[1],n],c):L(a.f,[e[0]-a.a[0],k[1]-a.a[1],e[2]],c)):e[0]<m[0]?(r=b.o[0][0]+(e[1]-f[1])/g*(b.o[1][0]-b.o[0][0]),q=e[2]>p?L(a.f,[f[0]-a.a[0],e[1]-a.a[1],p],c):e[2]<n?L(a.f,[f[0]-a.a[0],e[1]-a.a[1],n],c):L(a.f,[f[0]-a.a[0],e[1]-a.a[1],e[2]],c)):e[0]>l[0]?(r=b.o[0][1]+(e[1]-k[1])/g*(b.o[1][1]-b.o[0][1]),q=e[2]>p?L(a.f,[k[0]-a.a[0],e[1]-a.a[1],p],c):e[2]<n?L(a.f,[k[0]-a.a[0],
e[1]-a.a[1],n],c):L(a.f,[k[0]-a.a[0],e[1]-a.a[1],e[2]],c)):(k=(e[0]-f[0])/g,l=b.o[0][0]+(b.o[0][1]-b.o[0][0])*k,r=l+(e[1]-f[1])/g*(b.o[1][0]+(b.o[1][1]-b.o[1][0])*k-l),q=e[2]>p?L(a.f,[e[0]-a.a[0],e[1]-a.a[1],p],c):e[2]<n?L(a.f,[e[0]-a.a[0],e[1]-a.a[1],n],c):L(a.f,[e[0]-a.a[0],e[1]-a.a[1],e[2]],c));return!0==c?[q[0]*r*d,q[1]]:q*r*d}
function Ua(a,b){var c=a.T.get(b);if(!c||!ta(a.f,la(c.i,a.a)))return 0;if(!(1E6>c.o[0][0]))return Va(a,b,c);var d=Ra(a,c);if(!c.O||d<s.Db*a.Qd&&!0!=a.Sb){var e=a.oa.get(b),g;if(!(g=e)){a:{if(c.O)for(g=0;4>g;g++)if(c.O&1<<g&&a.oa.contains(M(b,g))){g=!0;break a}g=!1}g=!g}g?Qa(a,b,e,c):Va(a,b,c);return d}if(d=2.2>d)a:{if(a.oa.contains(b)&&1E6>c.o[0][0])for(d=0;4>d;d++)if(c.O&1<<d&&(g=M(b,d),e=a.oa.get(g),g=a.T.get(g),!e||!g)){d=!0;break a}d=!1}return d?(e=a.oa.get(b),Qa(a,b,e,c),0):Va(a,b,c)}
function Va(a,b,c){var d=a.de,e;e=c.i;var g=a.ee;null!=g?(g[0]=0.5*(e.h[0]+e.m[0]),g[1]=0.5*(e.h[1]+e.m[1]),e=g):e=[0.5*(e.h[0]+e.m[0]),0.5*(e.h[1]+e.m[1]),0.5*(e.h[2]+e.m[2])];g=a.f.a;e=Math.floor((Math.atan2(a.a[1]+g[1]-e[1],a.a[0]+g[0]-e[0])+Math.PI)/Math.PI*4);e=s.fa(e,0,7);for(var f=g=0;4>f;f++){var k=d[e][f];c.O&1<<k&&(g=Math.max(g,Ua(a,M(b,k))))}return g}
function Wa(a,b){var c=a.T.get(b);if(!c||!ta(a.f,la(c.i,a.a)))return 0;if(1E6>c.o[0][0]){var d=Ra(a,c);if(!c.O||d<s.Db)return d}for(var e=d=0;4>e;e++)c.O&1<<e&&(d=Math.max(d,Wa(a,M(b,e))));return d}function Xa(a,b,c){var d=a.T.get(b);if(!d||!ta(c,la(d.i,a.a)))return 9999999;if(1E6>d.o[0][0]){var e=Ra(a,d,!0);if(!d.O||e[0]<s.Db)return e[1]}for(var e=9999999,g=0;4>g;g++)d.O&1<<g&&(e=Math.min(e,Xa(a,M(b,g),c)));return e}
function Y(a){switch(a.d.n.Z){case "observer":a.g[1]=s.fa(a.g[1],-90,10);a.a[2]=s.fa(a.a[2],5,a.f.Ha);s.c.multiply(s.na(2,s.P(a.g[0])),s.na(0,s.P(a.g[1])),a.Ga);var b=[0,-a.a[2],0];s.c.Aa(a.Ga,b);a.va=[0,1,0];s.c.Aa(a.Ga,a.va);var c=s.gb(a.d,a.a,a.T,a.d.p.Pd);b[2]+=c[0]+a.Y;a.f.La(b);a.f.Ka(a.g);break;case "drone":a.g[1]=s.fa(a.g[1],-90,90);a.a[2]=s.fa(a.a[2],5,a.f.Ha);s.c.multiply(s.na(2,s.P(a.g[0])),s.na(0,s.P(a.g[1])),a.Ga);a.va=[0,1,0];s.c.Aa(a.Ga,a.va);b=a.f.a;a.f.La([0,0,a.a[2]+s.gb(a.d,[a.a[0]+
b[0],a.a[1]+b[1]],a.T)[0]]);a.f.Ka(a.g);break;case "manual":s.c.multiply(s.na(2,s.P(a.g[0])),s.na(0,s.P(a.g[1])),a.Ga),a.va=[0,1,0],s.c.Aa(a.Ga,a.va),a.f.La([0,0,a.a[2]]),a.f.Ka(a.g)}a.B=!0}function Z(a){var b=a.f.a;return a.f.ia()[2]-s.gb(a.d,[a.a[0]+b[0],a.a[1]+b[1]],a.T)[0]}function Ta(a){var b=a.f.ia();b[0]+=a.a[0];b[1]+=a.a[1];return b}
function Ya(a){if("manual"==a.d.n.Z)return!1;var b=Math.max(a.ea,5/a.ea*a.a[2]*0.1);if(Z(a)-a.Y<b){if(a.a[2]<b){var c=function(a,d,e){var l=0.5*(a+d);if(20<e)return l;this.a[2]=l;Y(this);return Z(this)-this.Y<b?c(a,l,e+1):c(l,d,e+1)}.bind(a);a.a[2]=c(a.a[2]+250,a.a[2],0)}else{var d=function(a,c,e){var l=0.5*(a+c);if(20<e)return l;this.g[1]=l;Y(this);return Z(this)-this.Y<b?d(a,l,e+1):d(l,c,e+1)}.bind(a);a.g[1]=d(-89,Math.min(-1,a.g[1]),0)}Y(a)}else{var e=0.5*a.wc;Math.max(e,20/e*a.a[2]*0.1)}return!1}
function Za(a){if("manual"==a.d.n.Z)return!1;var b=1E3,c=20,c=Math.max(20,0.1*a.a[2]);if(a.hb||-10<a.g[1]){var d=function(a,b,f){var k=0.5*(a+b);if(20<f)return k;this.g[1]=k;Y(this);return Z(this)<c?d(a,k,f+1):d(k,b,f+1)}.bind(a);Z(a)<c&&(a.g[1]=d(-89,Math.min(-1,a.g[1]),0),Y(a))}else for(;Z(a)<c&&0<b;)a.a[2]+=0.01,Y(a),b--;return!1}
function $a(a){var b=a.d.n;if("manual"==b.Z)return!1;switch(b.pa){case "aboveTerrainOnly":case "aboveTerrainByPixelSize":return Ya(a);case "aboveTerrainOnlyOld":return Za(a);default:for(var c,b=!1,d=a.d.n,e=1E3;(c>s.Db||0>Z(a))&&0<e;){b=!0;if("observer"==d.Z)if(a.hb||-10<a.g[1])250>a.a[2]?a.a[2]+=0.3:a.g[1]-=0.3;else{var g=s.P(a.g[0]),f=s.P(-a.g[1]);c=0.5/Math.sin(f);f=c*Math.cos(f);g=[-Math.sin(g),Math.cos(g),0];!0!=a.zb&&(a.a[0]+=f*g[0],a.a[1]+=f*g[1]);a.a[2]+=c}else a.a[2]+=0.5;Y(a);c=Wa(a,a.d.p.v);
e--}return b}}
function Oa(a,b){a.Ba=null!=b?b:!1;var c=a.d.n;if("drone"==c.Z&&!a.Ic){var d=s.gb(a.d,a.a,a.T);if(!d[1])return;a.a[2]+=d[0];a.Ic=!0}"aboveTerrainByPixelSize"!=c.pa&&(a.K=a.d.n.K,a.ea=a.d.n.ea);var e=!1,d=a.d.n;if("observer"==d.Z){if(a.a[2]<a.K){e=a.K-a.a[2];a.a[2]=a.K;var g=s.P(a.g[0]),f=s.P(-a.g[1]),k=0.5/Math.sin(f)*Math.cos(f),g=[-Math.sin(g),Math.cos(g),0];!0!=a.zb&&(a.a[0]+=k*g[0],a.a[1]+=k*g[1]);if(0<a.Y){var l=a.f,m=new qa(l.Yd,9,l.Va,l.Ha);m.La(l.ia());m.Ka(l.ob());m.Na=l.Na;m.B=!0;m.update();
Xa(a,a.d.p.v,m)>a.K&&(a.a[0]+=k*g[0]*e,a.a[1]+=k*g[1]*e,a.Y-=Math.sin(f)*e,0>a.Y&&(a.Y=0))}e=!0}a.a[2]>d.Lb&&(a.a[2]=d.Lb,e=!0)}a.g[1]<d.Nb&&(a.g[1]=d.Nb,e=!0);a.g[1]>d.Mb&&(a.g[1]=d.Mb,e=!0);!0==e&&Y(a);if("aboveTerrainOnly"==c.pa||"aboveTerrainByPixelSize"==c.pa)$a(a),a.j.clear(),Y(a),Ua(a,a.d.p.v),!0!=a.Ba&&Sa(a);else{do a.j.clear(),Y(a),Ua(a,a.d.p.v),!0!=a.Ba&&Sa(a);while($a(a))}a.T.trim(c.Kb/10);a.oa.trim(c.Kb);a.hb=!1}
h.update=function(){if(!0!=this.t){if(null==this.Q||"hidden"!=this.Q.style.visibility){var a=this.Q.getBoundingClientRect();this.s[0]==a.width&&this.s[1]==a.height||this.Vc();null!=this.Wc&&this.Wc();this.T.update();this.oa.update();!0==this.qd&&(this.ra=this.kc=this.lc=0,this.Ja=[],this.qb=this.rb=this.sb=0,this.fb++,10<=this.fb&&(a=Date.now(),null!=this.fc&&(this.Zb=0.5*(1E3/(a-this.fc)*this.fb+this.Zb)),this.fc=a));a=performance.now();if("aboveTerrainByPixelSize"==this.d.n.pa){var b=this.s[0]/
2;this.K=K(this.f)[0]*this.oc*b*2;this.ea=0.5*this.K}!0==this.B&&(b=this.j,b.e.viewport(0,0,b.e.tc,b.e.sc),Oa(this));if(!0==this.qd&&(this.Gb++,this.Cb+=performance.now()-a,100<=this.Gb&&(this.cd=this.Cb/this.Gb,this.Gb=this.Cb=0),null!=this.fd&&10<=this.fb&&(this.fb=0,!0==this.B))){var a="FPS: "+Math.round(this.Zb)+"<br/>Render time: "+Math.round(1E3*this.cd)+"<br/>Tile cache: "+Math.round(this.oa.size()/1048576)+"MB<br/>Metatile cache: "+Math.round(this.T.size()/1048576)+"MB<br/>GPU cache: "+Math.round(this.$b.size()/
1048576)+"MB<br/>- used: "+Math.round(this.sb/1048576)+"MB<br/>- used textures: "+Math.round(this.rb/1048576)+"MB<br/>- used meshes: "+Math.round(this.qb/1048576)+"MB<br/>Polygons: "+this.ra+"<br/>",b="Tiles: "+(this.lc+this.kc)+"<br/>",c;for(c in this.Ja)b+="LOD"+c+": "+this.Ja[c]+"<br/>";this.fd.innerHTML="<table style='width:305px'><tr><td>"+a+"</td><td>"+b+"</td></tr></table>"}this.B=!1}window.dd(this.update.bind(this))}};
h.qa=function(a){var b=sa(this.f),c=this.f.ia(),d=Ta(this),e=[0,0,0,1],e=s.c.xb(b,[a[0]-d[0]+c[0],a[1]-d[1]+c[1],a[2]-d[2]+c[2],1]);return 0!=e[3]?(a=[0,0,0],a[0]=0.5*(e[0]/e[3]+1)*this.s[0],a[1]=0.5*(-(e[1]/e[3])+1)*this.s[1],a[2]=e[2]/e[3],a):[0,0,0]};
h.pb=function(a,b){if(null==this.f)return[0,0,1];var c=[2*a/this.s[0]-1,1-2*b/this.s[1],1],d=[c[0],c[1],-1,1],e=s.c.create(),e=s.c.inverse(K(this.f)),c=[0,0,0,0];s.c.xb(e,d,c);c[2]=-1;c[3]=0;d=s.c.create();d=s.c.inverse(ra(this.f));e=[0,0,0,0];s.c.xb(d,c,e);return e=s.N.normalize([e[0],e[1],e[2]])};
h.cc=function(a,b){this.Hb=!0;var c=this.j.e;if(!0==this.Hb){var d=this.Ta;wa(this.j,this.ya);var e=[this.s[0],this.s[1]],g=d,f=d;c.clearColor(1,1,1,1);c.enable(c.DEPTH_TEST);c.viewport(0,0,d,d);c.clear(c.COLOR_BUFFER_BIT|c.DEPTH_BUFFER_BIT);this.s=[g,f];Oa(this,!0);g=e[0];f=e[1];c.clearColor(0,0,0,1);wa(this.j,null);d=this.f;d.Na=g/f;d.B=!0;this.s=[g,f];this.j.resize(this.s,!0);this.Hb=!1}if(c.checkFramebufferStatus(c.FRAMEBUFFER)!=c.FRAMEBUFFER_COMPLETE)return[0,0,0,0];f=g=0;g=Math.floor(this.Ta/
this.s[0]*a);f=Math.floor(this.Ta/this.s[1]*b);c=this.ya;f=this.Ta-f-1;null!=c.C?(c.j.bindTexture(c),wa(c.j,c),d=c.e,e=new Uint8Array(4),d.readPixels(g,f,1,1,d.RGBA,d.UNSIGNED_BYTE,e),wa(c.j,null),g=e):g=void 0;c=1/255*g[0]+g[1]+255*g[2]+65025*g[3];g=!(255==g[0]&&255==g[1]&&255==g[2]&&255==g[3]);f=this.pb(a,b);d=Ta(this);this.vb=[d[0]+f[0]*c,d[1]+f[1]*c,d[2]+f[2]*c];return[this.vb[0],this.vb[1],this.vb[2],g]};
h.mc=function(){this.Hb=!0;var a=this.j.e,b=this.s[0],c=this.s[1],d=new Uint8Array(b*c*4);a.readPixels(0,0,b,c,a.RGBA,a.UNSIGNED_BYTE,d);for(var a=new Uint8Array(b*c*4),e=0,g=0;g<c;g++){index2_=(c-1-g)*b*4;for(var f=0;f<b;f++)a[e]=d[index2_],a[e+1]=d[index2_+1],a[e+2]=d[index2_+2],a[e+3]=d[index2_+3],e+=4,index2_+=4}d=document.createElement("canvas");d.width=b;d.height=c;e=d.getContext("2d");b=e.createImageData(b,c);b.data.set(a);e.putImageData(b,0,0);window.open(d.toDataURL("image/jpeg"))};function ab(a,b,c,d){this.d=a;this.F=b;this.H=c;this.M=d;this.V=this.H.size()+d.naturalWidth*d.naturalHeight*3;this.Nc=c.fileSize();this.Lc=d.naturalWidth*d.naturalHeight*3}ab.prototype.w=function(){null!=this.H&&(this.H.w(),this.H=null);this.M=null};
ab.prototype.Qa=function(a,b){var c=w(this.d.p,this.F.k),d=c/2+this.F.q-a[0],c=c/2+this.F.r-a[1],e=this.H.i,g=b;null!=g?(g[0]=y(e,0),g[1]=0,g[2]=0,g[3]=0,g[4]=0,g[5]=y(e,1),g[6]=0,g[7]=0,g[8]=0,g[9]=0,g[10]=y(e,2),g[11]=0,g[12]=e.h[0]+d,g[13]=e.h[1]+c,g[14]=e.h[2],g[15]=1):(g=s.c.create(),s.c.multiply(s.Fa(e.h[0]+d,e.h[1]+c,e.h[2]),s.Eb(y(e,0),y(e,1),y(e,2)),g));return g};ab.prototype.size=function(){return this.V};s.sd=pa;
s.td=function(a,b,c,d){this.d=a;this.F=b;this.Ya=c;this.Xa=d;this.Xb=this.dc=this.Oc=!1;this.jb=function(){!0==this.Xb?null!=this.Xa&&this.Xa(this.F):!0==this.Oc&&!0==this.dc&&null!=this.Ya&&this.Ya(this.F,new ab(this.d,this.F,this.H,this.M))}.bind(this);this.M=new Image;this.M.onload=function(){!0!=this.d.t&&(this.dc=!0,this.jb())}.bind(this);this.M.onerror=function(){!0!=this.d.t&&(this.Xb=!0,this.jb())}.bind(this);this.M.crossOrigin="anonymous";!0==s.Tc?this.dc=!0:this.M.src=ha(this.d.p,this.F);
this.H=new W;this.Vd=function(){!0!=this.d.t&&(this.Oc=!0,this.jb())}.bind(this);this.Ud=function(){!0!=this.d.t&&(this.Xb=!0,this.jb())}.bind(this);this.H.load(fa(this.d.p,this.F),this.Vd,this.Ud)};function u(a,b,c,d){this.d=a;this.k=null!=b?b:0;this.q=null!=c?c:0;this.r=null!=d?d:0}function M(a,b){var c=w(a.d.p,a.k),d=a.q+c/2,c=a.r+c/2;switch(b){case 0:return new u(a.d,a.k+1,a.q,a.r);case 1:return new u(a.d,a.k+1,d,a.r);case 2:return new u(a.d,a.k+1,a.q,c);case 3:return new u(a.d,a.k+1,d,c)}}u.prototype.parent=function(){var a=w(this.d.p,this.k),b=this.d.p.v;return new u(this.d,this.k-1,b.q+((this.q-b.q)/a&-2)*a,b.r+((this.r-b.r)/a&-2)*a)};
u.prototype.isEqual=function(a){return this.k==a.k&&this.q==a.q&&this.r==a.r};function $(a,b,c,d,e,g){this.U=[];this.I=[];this.ba=[];this.qc=this.n=this.p=this.b=null;this.t=!1;this.Q=null;this.ub=g;"string"===typeof a?this.Q=document.getElementById(a):"object"===typeof a&&(this.Q=a);null==this.Q?null!=d&&d(!1,"DOM element does not exist"):null!=b&&bb(this,b,c,d,e)}
function bb(a,b,c,d,e){if(null==b||""==b)null!=d&&d(!1,"Map config does not exist");else{var g="";"string"===typeof b&&(g=b.split("?")[0].split("/").slice(0,-1).join("/")+"/");var f=null,k=null,l=function(){null==f||null==k&&null!=c||(this.p=new aa(this,f,g),this.n=new ja(k),this.qc=e,null!=this.b&&(this.b.w(),this.b=null),this.b=new Ha(this,this.Q,this.Wd.bind(this),this.ub),null!=d&&d(!0))}.bind(a),m=function(a){f=a;l()}.bind(a),n=function(a){k=a;l()}.bind(a),p=function(a){null!=d&&d(!1,a+" config not found")}.bind(a);
null!=c&&"string"===typeof c&&s.gc(c,n,p.bind(a,"browser"));"string"===typeof b&&s.gc(b,m,p.bind(a,"map"));"object"===typeof b&&(f=b);"object"===typeof c&&(k=c);null==f&&null==k||l()}}h=$.prototype;h.w=function(){this.b.w();this.t=!0};h.ie=function(a){if(!0!=this.t&&null!=this.b&&null!=this.b.f&&this.n.Z!=a){if("manual"==a){var b=s.Fe(this.b.a[0],this.b.a[1]);b[0]>this.b.a[2]&&(this.b.a[2]=b[0]+100)}this.n.Z=a;Y(this.b);this.U=[];this.ba=[];this.I=[]}};h.Fd=function(){return this.n.Z};
h.La=function(a,b,c){!0!=this.t&&null!=this.b&&(this.b.a=[a,b,c],Y(this.b))};h.ia=function(){return!0==this.t||null==this.b?[0,0,0]:[this.b.a[0],this.b.a[1],this.b.a[2]]};h.Ka=function(a,b,c){!0!=this.t&&null!=this.b&&(this.b.g=[a,b,c],Y(this.b))};h.ob=function(){return!0==this.t||null==this.b?[0,0,0]:this.b.g};h.ge=function(a,b){if(null!=this.b&&null!=this.b.f){var c=this.b.f;c.Dc=a;c.Va=20;c.Ha=b;c.B=!0;Y(this.b)}};h.he=function(a){!0!=this.t&&null!=this.b&&null!=this.b.f&&(this.n.pa=a,Y(this.b))};
h.Dd=function(){return this.n.pa};h.cc=function(a,b){return null==this.b?[0,0,0,!1]:this.b.cc(a,b,"all")};h.qa=function(a,b,c){return null==this.b?[0,0,0]:this.b.qa([a,b,c])};h.Ae=function(){return[[0,0],[1,0],[1,1],[0,1]]};h.pb=function(a,b){if(null==this.b)return[0,0,0,!1];var c=this.b.pb(a,b);return[Ta(this.b),c]};h.Ed=function(){if(null==this.b)return[[0,0,0],[0,1,0]];var a=this.b.va;return[Ta(this.b),[a[0],a[1],a[2]]]};h.Hd=function(a,b){if(!0!=this.t&&null!=this.b)return s.gb(this,[a,b],this.b.T)};
h.Xd=function(a,b){if(!0!=this.t&&null!=this.b){var c=Z(this.b)/800;a*=c;b*=c;var d=s.P(this.ob()[0]),c=[-Math.sin(d),Math.cos(d)],d=[Math.cos(d),Math.sin(d)];this.b.a[0]+=c[0]*b-d[0]*a;this.b.a[1]+=c[1]*b-d[1]*a;0<this.n.wa[0]&&this.U.push([c[0]*b-d[0]*a,c[1]*b-d[1]*a]);Y(this.b)}};h.rotate=function(a,b,c){!0!=this.t&&null!=this.b&&(null==c&&(c=0),this.b.g[0]+=0.3*-a,this.b.g[1]+=0.3*-b,this.b.g[2]+=0.3*c,0<this.n.wa[1]&&this.I.push([0.3*-a,0.3*-b,0.3*c]),this.b.hb=!0,Y(this.b))};
h.zoom=function(a){!0!=this.t&&null!=this.b&&(a=1+0.001*a,this.b.a[2]*=a,0<this.n.wa[2]&&this.ba.push([a]),Y(this.b))};h.mc=function(){!0!=this.t&&null!=this.b&&this.b.mc()};
h.je=function(a,b){if(!0!=this.t&&null!=this.b){switch(a){case "cameraHeightOffset":this.b.Y=b;break;case "drawOnlyHeightmap":this.b.bc=b;break;case "noForwardMovement":this.b.zb=b;break;case "texelSize":this.b.oc=b*s.kd;break;case "drawBBoxes":this.b.Ob=b;break;case "drawWireframe":this.b.Pa=b;break;case "drawLods":this.b.Rb=b;break;case "drawPositions":this.b.Tb=b;break;case "drawTexelSize":this.b.Ub=b;break;case "drawFaceCount":this.b.Qb=b;break;case "drawDistance":this.b.Pb=b;break;case "drawMaxLod":this.b.Sb=
b;break;case "drawTextureSize":this.b.Vb=b;break;case "minDistance":this.b.K=b,this.b.wc=b,this.b.ea=0.5*b}Y(this.b)}};
h.Gd=function(a){if(!0!=this.t&&null!=this.b){switch(a){case "cameraHeightOffset":return this.b.Y;case "drawOnlyHeightmap":return this.b.bc;case "noForwardMovement":return this.b.zb;case "minDistance":return this.b.K;case "texelSize":return this.b.oc;case "drawBBoxes":return this.b.Ob;case "drawWireframe":return this.b.Pa;case "drawLods":return this.b.Rb;case "drawPositions":return this.b.Tb;case "drawTexelSize":return this.b.Ub;case "drawFaceCount":return this.b.Qb;case "drawDistance":return this.b.Pb;
case "drawMaxLod":return this.b.Sb;case "drawTextureSize":return this.b.Vb}return null}};
h.Wd=function(){if(!0!=this.t&&null!=this.b){var a=!1,b=this.n.wa[0],c=this.n.wa[1],d=this.n.wa[2];0<this.I.length&&0==this.U.length&&0==this.ba.length&&(this.b.hb=!0);for(var e=0;e<this.U.length;e++)this.U[e][0]*=b,this.U[e][1]*=b,this.b.a[0]+=this.U[e][0],this.b.a[1]+=this.U[e][1],0.01>Math.abs(this.U[e][0])+Math.abs(this.U[e][1])&&(this.U.splice(e,1),e--),a=!0;for(e=0;e<this.ba.length;e++)this.ba[e][0]+=(1-this.ba[e][0])*(1-d),this.b.a[2]*=this.ba[e][0],this.b.a[2]=Math.min(this.b.a[2],4E5),0.001>
Math.abs(1-this.ba[e][0])&&(this.ba.splice(e,1),e--),a=!0;for(e=0;e<this.I.length;e++)this.I[e][0]*=c,this.I[e][1]*=c,this.I[e][2]*=c,this.b.g[0]+=this.I[e][0],this.b.g[1]+=this.I[e][1],this.b.g[2]+=this.I[e][2],0.01>Math.abs(this.I[e][0])+Math.abs(this.I[e][1])+Math.abs(this.I[e][2])&&(this.I.splice(e,1),e--),a=!0;!0==a&&Y(this.b);null!=this.qc&&this.qc(this.b.B)}};
s.yd=function(){var a=document.createElement("canvas");if(null==a)return!1;a.width=1024;a.height=768;if(null==a.getContext)return!1;var b=null;try{b=a.getContext("webgl")||a.getContext("experimental-webgl")}catch(c){return!1}return b?!0:!1};s.Browser=$;$.prototype.setControlMode=$.prototype.ie;$.prototype.getControlMode=$.prototype.Fd;$.prototype.setPosition=$.prototype.La;$.prototype.getPosition=$.prototype.ia;$.prototype.setOrientation=$.prototype.Ka;$.prototype.getOrientation=$.prototype.ob;
$.prototype.setCamera=$.prototype.ge;$.prototype.setCameraConstrainMode=$.prototype.he;$.prototype.getCameraConstrainMode=$.prototype.Dd;$.prototype.hitTest=$.prototype.cc;$.prototype.project=$.prototype.qa;$.prototype.setOption=$.prototype.je;$.prototype.getOption=$.prototype.Gd;$.prototype.getScreenRay=$.prototype.pb;$.prototype.getCameraVector=$.prototype.Ed;$.prototype.getTerrainHeight=$.prototype.Hd;$.prototype.saveScreenshot=$.prototype.mc;$.prototype.visibleArea=$.prototype.Ae;
$.prototype.pan=$.prototype.Xd;$.prototype.rotate=$.prototype.rotate;$.prototype.zoom=$.prototype.zoom;$.prototype.kill=$.prototype.w;s.checkSupport=s.yd;s.loadJSON=s.gc;
